// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s AddStubOK) Validate() error {
	switch s.Type {
	case ListIDAddStubOK:
		if err := s.ListID.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s AddStubReq) Validate() error {
	switch s.Type {
	case StubListAddStubReq:
		if err := s.StubList.Validate(); err != nil {
			return err
		}
		return nil
	case StubAddStubReq:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s ListID) Validate() error {
	alias := ([]ID)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s SearchStubsReq) Validate() error {
	switch s.Type {
	case StubListSearchStubsReq:
		if err := s.StubList.Validate(); err != nil {
			return err
		}
		return nil
	case StubSearchStubsReq:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s StubList) Validate() error {
	alias := ([]Stub)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
