# yaml-language-server: $schema=https://bavix.github.io/gripmock/schema/stub.json

- service: inventory.InventoryService
  method: GetResourceDecorationByIPsStream
  input:
    ignoreArrayOrder: true
    equals:
      k8s_cluster_id: "test-equals-ignore"
      ips: ["10.0.3.1", "10.0.3.2"]
  output:
    data:
      ips_to_decorations:
        "10.0.3.1":
          decoration: "web-frontend"
          environment: "production"
        "10.0.3.2":
          decoration: "api-backend"
          environment: "staging"
