// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: examples/sdk/negotiation/v1/negotiation.proto

package negotiationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HaggleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	PriceCents    int64                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaggleRequest) Reset() {
	*x = HaggleRequest{}
	mi := &file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaggleRequest) ProtoMessage() {}

func (x *HaggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaggleRequest.ProtoReflect.Descriptor instead.
func (*HaggleRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_negotiation_v1_negotiation_proto_rawDescGZIP(), []int{0}
}

func (x *HaggleRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *HaggleRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

type HaggleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceCents    int64                  `protobuf:"varint,1,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Verdict       string                 `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaggleResponse) Reset() {
	*x = HaggleResponse{}
	mi := &file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaggleResponse) ProtoMessage() {}

func (x *HaggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaggleResponse.ProtoReflect.Descriptor instead.
func (*HaggleResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_negotiation_v1_negotiation_proto_rawDescGZIP(), []int{1}
}

func (x *HaggleResponse) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *HaggleResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_examples_sdk_negotiation_v1_negotiation_proto protoreflect.FileDescriptor

const file_examples_sdk_negotiation_v1_negotiation_proto_rawDesc = "" +
	"\n" +
	"-examples/sdk/negotiation/v1/negotiation.proto\x12\x0enegotiation.v1\"I\n" +
	"\rHaggleRequest\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x03R\n" +
	"priceCents\"K\n" +
	"\x0eHaggleResponse\x12\x1f\n" +
	"\vprice_cents\x18\x01 \x01(\x03R\n" +
	"priceCents\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict2a\n" +
	"\x12NegotiationService\x12K\n" +
	"\x06Haggle\x12\x1d.negotiation.v1.HaggleRequest\x1a\x1e.negotiation.v1.HaggleResponse(\x010\x01BHZFgithub.com/bavix/gripmock/v3/examples/sdk/negotiation/v1;negotiationv1b\x06proto3"

var (
	file_examples_sdk_negotiation_v1_negotiation_proto_rawDescOnce sync.Once
	file_examples_sdk_negotiation_v1_negotiation_proto_rawDescData []byte
)

func file_examples_sdk_negotiation_v1_negotiation_proto_rawDescGZIP() []byte {
	file_examples_sdk_negotiation_v1_negotiation_proto_rawDescOnce.Do(func() {
		file_examples_sdk_negotiation_v1_negotiation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_sdk_negotiation_v1_negotiation_proto_rawDesc), len(file_examples_sdk_negotiation_v1_negotiation_proto_rawDesc)))
	})
	return file_examples_sdk_negotiation_v1_negotiation_proto_rawDescData
}

var file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_sdk_negotiation_v1_negotiation_proto_goTypes = []any{
	(*HaggleRequest)(nil),  // 0: negotiation.v1.HaggleRequest
	(*HaggleResponse)(nil), // 1: negotiation.v1.HaggleResponse
}
var file_examples_sdk_negotiation_v1_negotiation_proto_depIdxs = []int32{
	0, // 0: negotiation.v1.NegotiationService.Haggle:input_type -> negotiation.v1.HaggleRequest
	1, // 1: negotiation.v1.NegotiationService.Haggle:output_type -> negotiation.v1.HaggleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_sdk_negotiation_v1_negotiation_proto_init() }
func file_examples_sdk_negotiation_v1_negotiation_proto_init() {
	if File_examples_sdk_negotiation_v1_negotiation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_sdk_negotiation_v1_negotiation_proto_rawDesc), len(file_examples_sdk_negotiation_v1_negotiation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_sdk_negotiation_v1_negotiation_proto_goTypes,
		DependencyIndexes: file_examples_sdk_negotiation_v1_negotiation_proto_depIdxs,
		MessageInfos:      file_examples_sdk_negotiation_v1_negotiation_proto_msgTypes,
	}.Build()
	File_examples_sdk_negotiation_v1_negotiation_proto = out.File
	file_examples_sdk_negotiation_v1_negotiation_proto_goTypes = nil
	file_examples_sdk_negotiation_v1_negotiation_proto_depIdxs = nil
}
