version: "2"
run:
  timeout: 5m
  go: "1.25"

linters:
  default: all
  disable:
    - wsl  # deprecated, replaced by wsl_v5
    - exhaustruct  # too strict for this project - requires all struct fields
    - revive  # too strict for this project - requires comments on all exported items
    - varnamelen  # too strict for this project - requires longer variable names
    - noinlineerr  # too strict for this project - requires separate error assignment
    - wrapcheck  # too strict for this project - requires wrapping all errors
  settings:
    lll:
      tab-width: 1
      line-length: 140
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com
            - google.golang.org

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/bavix)
