OPENAPI=api/api.yaml

.PHONY: *

version=latest
GOLANGCI_LINT=go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2

build:
	docker buildx build --load -t bavix/gripmock:${version} .

build-ui:
	cd ui && npm ci && npm run build

# -p 4 caps how many packages run at once: the end-to-end suites each boot a
# real gripmock, and under -race an unbounded fan-out starves their health checks.
test:
	go test -race -cover -p 4 ./...

lint: lint-clean
	$(GOLANGCI_LINT) run --color always

lint-fix: lint-clean
	$(GOLANGCI_LINT) run --color always --fix

lint-clean:
	$(GOLANGCI_LINT) cache clean

plugins:
	mkdir -p plugins; \
	for dir in examples/plugins/*; do \
		[ -d $$dir ] && go build -buildmode=plugin -o plugins/$$(basename $$dir).so $$dir/*.go; \
	done

semgrep:
	docker run --rm -v $$(pwd):/src bavix/semgrep:master semgrep scan --error --config=p/golang -f /semgrep-go

bench-run:
	cd bench && ./run.sh

bench-chart:
	cd bench && go run .

bench-calibrate:
	cd bench && ./run.sh calibrate

bench: bench-run bench-chart

# Override to pin a specific codegen version, e.g. make gen-rest OAPI_CODEGEN=...@v2.5.0
OAPI_CODEGEN ?= github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

gen-rest:
	go run $(OAPI_CODEGEN) -generate gorilla,types -package rest ${OPENAPI} > internal/domain/rest/api.gen.go
	sed 's/interface{}/any/g' internal/domain/rest/api.gen.go > internal/domain/rest/api.gen.go.tmp
	mv internal/domain/rest/api.gen.go.tmp internal/domain/rest/api.gen.go
	gofmt -w internal/domain/rest/api.gen.go
	goimports -w internal/domain/rest/api.gen.go

PROTOBUF_REPO=/tmp/gm-protobuf-repo
GOOGLEAPIS_REPO=/tmp/gm-googleapis-sdk

PROTOBUF_EXCLUDE_ARGS=\
	--exclude 'google/protobuf/compiler/**' \
	--exclude '**/*test*.proto' \
	--exclude '**/test_protos/**' \
	--exclude '**/sample_*.proto' \
	--exclude '**/internal_*.proto' \
	--exclude '**/late_loaded_*.proto'

GOOGLEAPIS_EXCLUDE_ARGS=\
	--exclude 'preview/**'

# Both repositories are cloned at HEAD, so regenerating on a different day
# produces a different bundle (upstream googleapis rotates Google Ads API
# versions in and out). SOURCES.md records which revisions produced the
# committed bundles, so a surprising diff can be traced back.
gen-imports:
	rm -rf $(PROTOBUF_REPO) $(GOOGLEAPIS_REPO)
	touch internal/pbs/protobuf.pbs internal/pbs/googleapis.pbs
	git clone --depth=1 https://github.com/protocolbuffers/protobuf.git $(PROTOBUF_REPO)
	git clone --depth=1 https://github.com/googleapis/googleapis.git $(GOOGLEAPIS_REPO)
	go run main.go proto export \
		--root $(PROTOBUF_REPO)/src \
		$(PROTOBUF_EXCLUDE_ARGS) \
		--out internal/pbs/protobuf.pbs
	go run main.go proto export \
		--root $(GOOGLEAPIS_REPO) \
		--import-root $(PROTOBUF_REPO)/src \
		$(GOOGLEAPIS_EXCLUDE_ARGS) \
		--out internal/pbs/googleapis.pbs
	printf '# Descriptor bundle sources\n\nGenerated by `make gen-imports`. Do not edit by hand.\n\n| Bundle | Repository | Revision | Date |\n|---|---|---|---|\n| protobuf.pbs | protocolbuffers/protobuf | %s | %s |\n| googleapis.pbs | googleapis/googleapis | %s | %s |\n' \
		"$$(git -C $(PROTOBUF_REPO) rev-parse HEAD)" "$$(git -C $(PROTOBUF_REPO) log -1 --format=%cs)" \
		"$$(git -C $(GOOGLEAPIS_REPO) rev-parse HEAD)" "$$(git -C $(GOOGLEAPIS_REPO) log -1 --format=%cs)" \
		> internal/pbs/SOURCES.md
	rm -rf $(PROTOBUF_REPO) $(GOOGLEAPIS_REPO)

SDK_EXAMPLES=billing telemetry ingest negotiation onboarding

gen-sdk-examples-protos:
	for name in $(SDK_EXAMPLES); do \
		protoc --proto_path=. \
			--go_out=. --go_opt=paths=source_relative \
			--go-grpc_out=. --go-grpc_opt=paths=source_relative \
			examples/sdk/$$name/v1/$$name.proto; \
	done

