package proxycapture

import (
	"bytes"
	"encoding/json"
	"strings"

	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"

	"github.com/bavix/gripmock/v3/internal/infra/protoset"
	"github.com/bavix/gripmock/v3/internal/infra/stuber"
)

func MessageToMap(message proto.Message) map[string]any {
	if message == nil {
		return nil
	}

	encoded, err := protoset.GlobalTypeResolver().Marshal(message)
	if err != nil {
		return nil
	}

	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()

	out := make(map[string]any)
	if err = decoder.Decode(&out); err != nil {
		return nil
	}

	return out
}

// MessageToAny is like MessageToMap but preserves the JSON value's outermost
// shape. For well-known types whose JSON encoding is a primitive (e.g. a
// google.protobuf.Timestamp becomes an RFC3339 string) the returned value is
// that scalar wrapped in any; for regular messages it is a map[string]any.
func MessageToAny(message proto.Message) any {
	if message == nil {
		return nil
	}

	encoded, err := protoset.GlobalTypeResolver().Marshal(message)
	if err != nil {
		return nil
	}

	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()

	var out any
	if err = decoder.Decode(&out); err != nil {
		return nil
	}

	return out
}

func ResponseHeaders(head metadata.MD, tail metadata.MD) map[string]string {
	if len(head) == 0 && len(tail) == 0 {
		return nil
	}

	out := make(map[string]string)
	appendMetadata(out, head, nil)
	appendMetadata(out, tail, nil)

	if len(out) == 0 {
		return nil
	}

	return out
}

// ResponseMetadata is the header/trailer pair captured from an upstream call.
// The two are kept apart so a replayed stub sends each back on the wire where
// the original arrived; merging them would turn a trailer into a header and,
// when a key appears in both, splice the two values together.
type ResponseMetadata struct {
	Headers  map[string]string
	Trailers map[string]string
}

// reservedTrailerKeys are generated by gRPC for every call and carry no stub
// meaning; replaying them would fight the status the stub itself sets.
//
//nolint:gochecknoglobals
var reservedTrailerKeys = map[string]struct{}{
	"grpc-status":             {},
	"grpc-message":            {},
	"grpc-status-details-bin": {},
}

// reservedHeaderKeys are set by the gRPC stack on every response and describe the
// transport, not the stub. Replaying them would write a transport header from
// stub data, and they are noise in every captured stub file.
//
//nolint:gochecknoglobals
var reservedHeaderKeys = map[string]struct{}{
	"content-type":         {},
	"content-length":       {},
	"grpc-encoding":        {},
	"grpc-accept-encoding": {},
}

func CaptureMetadata(head metadata.MD, tail metadata.MD) ResponseMetadata {
	return ResponseMetadata{
		Headers:  flattenMetadata(head, reservedHeaderKeys),
		Trailers: flattenMetadata(tail, reservedTrailerKeys),
	}
}

func flattenMetadata(source metadata.MD, skip map[string]struct{}) map[string]string {
	if len(source) == 0 {
		return nil
	}

	out := make(map[string]string, len(source))
	appendMetadata(out, source, skip)

	if len(out) == 0 {
		return nil
	}

	return out
}

func appendMetadata(out map[string]string, source metadata.MD, skip map[string]struct{}) {
	for key, values := range source {
		if len(values) == 0 {
			continue
		}

		if _, skipped := skip[strings.ToLower(key)]; skipped {
			continue
		}

		joined := strings.Join(values, ";")
		if previous, ok := out[key]; ok && previous != "" {
			out[key] = previous + ";" + joined
		} else {
			out[key] = joined
		}
	}
}

// buildProxyStub assembles the common proxy-captured stub skeleton and applies
// the call error. clearData drops Output.Data when the call failed (true for
// data-carrying responses, false for streamed ones).
func buildProxyStub(
	service, method, session string,
	requestHeaders map[string]any,
	input stuber.InputData,
	inputs []stuber.InputData,
	output stuber.Output,
	callErr error,
	clearData bool,
) *stuber.Stub {
	stub := &stuber.Stub{
		Service: service,
		Method:  method,
		Session: session,
		Source:  stuber.SourceProxy,
		Headers: stuber.InputHeader{Equals: requestHeaders},
		Input:   input,
		Inputs:  inputs,
		Output:  output,
	}

	applyStatusError(&stub.Output, callErr, clearData)

	return stub
}

func BuildUnaryStub(
	service string,
	method string,
	session string,
	request map[string]any,
	requestHeaders map[string]any,
	response any,
	responseMeta ResponseMetadata,
	callErr error,
) *stuber.Stub {
	return buildProxyStub(service, method, session, requestHeaders,
		stuber.InputData{Equals: request}, nil,
		stuber.Output{Data: response, Headers: responseMeta.Headers, Trailers: responseMeta.Trailers}, callErr, true)
}

func BuildServerStreamStub(
	service string,
	method string,
	session string,
	request map[string]any,
	requestHeaders map[string]any,
	responses []any,
	responseMeta ResponseMetadata,
	callErr error,
) *stuber.Stub {
	return buildProxyStub(service, method, session, requestHeaders,
		stuber.InputData{Equals: request}, nil,
		stuber.Output{Stream: toStreamOutput(responses), Headers: responseMeta.Headers, Trailers: responseMeta.Trailers}, callErr, false)
}

func BuildClientStreamStub(
	service string,
	method string,
	session string,
	requests []map[string]any,
	requestHeaders map[string]any,
	response any,
	responseMeta ResponseMetadata,
	callErr error,
) *stuber.Stub {
	return buildProxyStub(service, method, session, requestHeaders,
		stuber.InputData{}, toInputs(requests),
		stuber.Output{Data: response, Headers: responseMeta.Headers, Trailers: responseMeta.Trailers}, callErr, true)
}

func BuildBidiStub(
	service string,
	method string,
	session string,
	requests []map[string]any,
	requestHeaders map[string]any,
	responses []any,
	responseMeta ResponseMetadata,
	callErr error,
) *stuber.Stub {
	return buildProxyStub(service, method, session, requestHeaders,
		stuber.InputData{}, toInputs(requests),
		stuber.Output{Stream: toStreamOutput(responses), Headers: responseMeta.Headers, Trailers: responseMeta.Trailers}, callErr, false)
}

func toInputs(requests []map[string]any) []stuber.InputData {
	inputs := make([]stuber.InputData, 0, len(requests))
	for _, request := range requests {
		inputs = append(inputs, stuber.InputData{Equals: request})
	}

	return inputs
}

func toStreamOutput(responses []any) []any {
	streamOutput := make([]any, 0, len(responses))
	streamOutput = append(streamOutput, responses...)

	return streamOutput
}

func applyStatusError(output *stuber.Output, callErr error, clearData bool) {
	if output == nil || callErr == nil {
		return
	}

	st := status.Convert(callErr)
	code := st.Code()

	output.Code = &code
	output.Error = st.Message()
	output.Details = statusDetailsToMaps(callErr)

	if clearData {
		output.Data = nil
	}
}

func statusDetailsToMaps(callErr error) []map[string]any {
	if callErr == nil {
		return nil
	}

	st := status.Convert(callErr)

	details := st.Details()
	if len(details) == 0 {
		return nil
	}

	out := make([]map[string]any, 0, len(details))
	for _, detail := range details {
		msg, ok := detail.(proto.Message)
		if !ok {
			continue
		}

		mapped := MessageToMap(msg)
		if mapped == nil {
			continue
		}

		typeURL := "type.googleapis.com/" + string(msg.ProtoReflect().Descriptor().FullName())
		mapped["type"] = typeURL

		out = append(out, mapped)
	}

	if len(out) == 0 {
		return nil
	}

	return out
}
