package yaml2json

import (
	"bytes"
	"encoding/json"
	"text/template"

	"github.com/cristalhq/base64"
	"github.com/google/uuid"
)

type engine struct{}

// Execute executes a Go template with the given name and data.
// It returns the generated bytes and an error if any.
func (e *engine) Execute(name string, data []byte) ([]byte, error) {
	// Execute a Go template with the given name and data.
	// It returns the generated bytes and an error if any.
	t := template.New(name).Funcs(e.funcMap())

	t, err := t.Parse(string(data))
	if err != nil {
		return nil, err
	}

	var buffer bytes.Buffer
	if err := t.Execute(&buffer, nil); err != nil {
		return nil, err
	}

	return buffer.Bytes(), nil
}

// uuid2int64 converts a UUID string to a map of two int64 values.
// It returns an empty string if there is an error.
func (e *engine) uuid2int64(str string) string {
	v := uuid.MustParse(str)

	//nolint:mnd
	high := int64(v[0]) | int64(v[1])<<8 | int64(v[2])<<16 | int64(v[3])<<24 |
		int64(v[4])<<32 | int64(v[5])<<40 | int64(v[6])<<48 | int64(v[7])<<56

	//nolint:mnd
	low := int64(v[8]) | int64(v[9])<<8 | int64(v[10])<<16 | int64(v[11])<<24 |
		int64(v[12])<<32 | int64(v[13])<<40 | int64(v[14])<<48 | int64(v[15])<<56

	if int64JSON, err := json.Marshal(map[string]int64{
		"high": high,
		"low":  low,
	}); err == nil {
		return string(int64JSON)
	}

	return ""
}

// uuid2base64 converts a UUID string to a base64 string.
func (e *engine) uuid2base64(input string) string {
	return e.bytes2base64(e.uuid2bytes(input))
}

// uuid2bytes converts a UUID string to a byte slice.
func (e *engine) uuid2bytes(input string) []byte {
	v := uuid.MustParse(input)

	return v[:]
}

func (e *engine) bytes(v string) []byte {
	return []byte(v)
}

func (e *engine) string2base64(v string) string {
	return base64.StdEncoding.EncodeToString(e.bytes(v))
}

func (e *engine) bytes2base64(v []byte) string {
	return base64.StdEncoding.EncodeToString(v)
}

func (e *engine) funcMap() template.FuncMap {
	return template.FuncMap{
		"bytes":         e.bytes,
		"string2base64": e.string2base64,
		"bytes2base64":  e.bytes2base64,
		"uuid2base64":   e.uuid2base64,
		"uuid2bytes":    e.uuid2bytes,
		"uuid2int64":    e.uuid2int64,
	}
}
