// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: examples/sdk/ingest/v1/ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBatchRequest) Reset() {
	*x = UploadBatchRequest{}
	mi := &file_examples_sdk_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBatchRequest) ProtoMessage() {}

func (x *UploadBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBatchRequest.ProtoReflect.Descriptor instead.
func (*UploadBatchRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBatchRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UploadBatchRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UploadBatchRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadBatchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UploadBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBatchResponse) Reset() {
	*x = UploadBatchResponse{}
	mi := &file_examples_sdk_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBatchResponse) ProtoMessage() {}

func (x *UploadBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBatchResponse.ProtoReflect.Descriptor instead.
func (*UploadBatchResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *UploadBatchResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *UploadBatchResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_examples_sdk_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_examples_sdk_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"#examples/sdk/ingest/v1/ingest.proto\x12\tingest.v1\"p\n" +
	"\x12UploadBatchRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"h\n" +
	"\x13UploadBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x05R\brejected2_\n" +
	"\rIngestService\x12N\n" +
	"\vUploadBatch\x12\x1d.ingest.v1.UploadBatchRequest\x1a\x1e.ingest.v1.UploadBatchResponse(\x01B>Z<github.com/bavix/gripmock/v3/examples/sdk/ingest/v1;ingestv1b\x06proto3"

var (
	file_examples_sdk_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_examples_sdk_ingest_v1_ingest_proto_rawDescData []byte
)

func file_examples_sdk_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_examples_sdk_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_examples_sdk_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_sdk_ingest_v1_ingest_proto_rawDesc), len(file_examples_sdk_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_examples_sdk_ingest_v1_ingest_proto_rawDescData
}

var file_examples_sdk_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_sdk_ingest_v1_ingest_proto_goTypes = []any{
	(*UploadBatchRequest)(nil),  // 0: ingest.v1.UploadBatchRequest
	(*UploadBatchResponse)(nil), // 1: ingest.v1.UploadBatchResponse
}
var file_examples_sdk_ingest_v1_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.v1.IngestService.UploadBatch:input_type -> ingest.v1.UploadBatchRequest
	1, // 1: ingest.v1.IngestService.UploadBatch:output_type -> ingest.v1.UploadBatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_sdk_ingest_v1_ingest_proto_init() }
func file_examples_sdk_ingest_v1_ingest_proto_init() {
	if File_examples_sdk_ingest_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_sdk_ingest_v1_ingest_proto_rawDesc), len(file_examples_sdk_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_sdk_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_examples_sdk_ingest_v1_ingest_proto_depIdxs,
		MessageInfos:      file_examples_sdk_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_examples_sdk_ingest_v1_ingest_proto = out.File
	file_examples_sdk_ingest_v1_ingest_proto_goTypes = nil
	file_examples_sdk_ingest_v1_ingest_proto_depIdxs = nil
}
