// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: ms.proto

package ms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V1            [][]byte               `protobuf:"bytes,1,rep,name=v1,proto3" json:"v1,omitempty"`
	V2            []string               `protobuf:"bytes,2,rep,name=v2,proto3" json:"v2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ms_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetV1() [][]byte {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *Request) GetV2() []string {
	if x != nil {
		return x.V2
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_ms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_ms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_ms_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_ms_proto protoreflect.FileDescriptor

const file_ms_proto_rawDesc = "" +
	"\n" +
	"\bms.proto\x12\x02ms\")\n" +
	"\aRequest\x12\x0e\n" +
	"\x02v1\x18\x01 \x03(\fR\x02v1\x12\x0e\n" +
	"\x02v2\x18\x02 \x03(\tR\x02v2\"\x1b\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code22\n" +
	"\fMicroService\x12\"\n" +
	"\bSayHello\x12\v.ms.Request\x1a\t.ms.ReplyB/Z-github.com/bavix/gripmock/protogen/example/msb\x06proto3"

var (
	file_ms_proto_rawDescOnce sync.Once
	file_ms_proto_rawDescData []byte
)

func file_ms_proto_rawDescGZIP() []byte {
	file_ms_proto_rawDescOnce.Do(func() {
		file_ms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ms_proto_rawDesc), len(file_ms_proto_rawDesc)))
	})
	return file_ms_proto_rawDescData
}

var file_ms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ms_proto_goTypes = []any{
	(*Request)(nil), // 0: ms.Request
	(*Reply)(nil),   // 1: ms.Reply
}
var file_ms_proto_depIdxs = []int32{
	0, // 0: ms.MicroService.SayHello:input_type -> ms.Request
	1, // 1: ms.MicroService.SayHello:output_type -> ms.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ms_proto_init() }
func file_ms_proto_init() {
	if File_ms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ms_proto_rawDesc), len(file_ms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ms_proto_goTypes,
		DependencyIndexes: file_ms_proto_depIdxs,
		MessageInfos:      file_ms_proto_msgTypes,
	}.Build()
	File_ms_proto = out.File
	file_ms_proto_goTypes = nil
	file_ms_proto_depIdxs = nil
}
