// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Liveness implements liveness operation.
	//
	// The test says that the service is alive and yet.
	//
	// GET /liveness
	Liveness(ctx context.Context) (*MessageOK, error)
	// Readiness implements readiness operation.
	//
	// The test indicates readiness to receive traffic.
	//
	// GET /readiness
	Readiness(ctx context.Context) (*MessageOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
