// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package rest

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	gptypes "github.com/bavix/gripmock/v3/internal/infra/types"
	uuid "github.com/google/uuid"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	codes "google.golang.org/grpc/codes"
)

// Defines values for MethodMethodType.
const (
	BidiStreaming   MethodMethodType = "bidi_streaming"
	ClientStreaming MethodMethodType = "client_streaming"
	ServerStreaming MethodMethodType = "server_streaming"
	Unary           MethodMethodType = "unary"
)

// Valid indicates whether the value is a known member of the MethodMethodType enum.
func (e MethodMethodType) Valid() bool {
	switch e {
	case BidiStreaming:
		return true
	case ClientStreaming:
		return true
	case ServerStreaming:
		return true
	case Unary:
		return true
	default:
		return false
	}
}

// Defines values for ProtoFieldSchemaCardinality.
const (
	Optional ProtoFieldSchemaCardinality = "optional"
	Repeated ProtoFieldSchemaCardinality = "repeated"
	Required ProtoFieldSchemaCardinality = "required"
)

// Valid indicates whether the value is a known member of the ProtoFieldSchemaCardinality enum.
func (e ProtoFieldSchemaCardinality) Valid() bool {
	switch e {
	case Optional:
		return true
	case Repeated:
		return true
	case Required:
		return true
	default:
		return false
	}
}

// Defines values for StubEffectAction.
const (
	Delete StubEffectAction = "delete"
	Upsert StubEffectAction = "upsert"
)

// Valid indicates whether the value is a known member of the StubEffectAction enum.
func (e StubEffectAction) Valid() bool {
	switch e {
	case Delete:
		return true
	case Upsert:
		return true
	default:
		return false
	}
}

// AddDescriptorsResponse Result of registering an uploaded FileDescriptorSet.
type AddDescriptorsResponse struct {
	// Message Human-readable result of the upload.
	Message string `json:"message"`

	// ServiceIDs Service IDs (e.g. helloworld.Greeter) registered. Use DELETE /services/{serviceID} to remove.
	ServiceIDs []string `json:"serviceIDs"`

	// Time Server time when the response was produced (RFC 3339).
	Time time.Time `json:"time"`
}

// CallRecord One gRPC call the server answered.
type CallRecord struct {
	// Code gRPC status code (e.g., 0 for OK, 5 for NotFound)
	Code *int `json:"code,omitempty"`

	// ElapsedMs Handler duration in milliseconds
	ElapsedMs *int64 `json:"elapsedMs,omitempty"`

	// Error gRPC status message, empty when the call succeeded.
	Error *string `json:"error,omitempty"`

	// Method gRPC method name.
	Method *string `json:"method,omitempty"`

	// Request Deprecated: use requests for streaming calls
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Request *map[string]any `json:"request,omitempty"`

	// Requests Request messages for streaming calls (client stream, bidi stream)
	Requests *[]map[string]any `json:"requests,omitempty"`

	// Response Deprecated: use responses for streaming calls
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Response *map[string]any `json:"response,omitempty"`

	// ResponseHeaders Normalized response metadata (header+trailer) the call answered with
	ResponseHeaders map[string]string `json:"responseHeaders,omitempty"`

	// Responses Response messages for streaming calls (server stream, bidi stream)
	Responses *[]map[string]any `json:"responses,omitempty"`

	// Service Fully qualified gRPC service name.
	Service *string `json:"service,omitempty"`

	// Session Session ID (empty = global)
	Session *string `json:"session,omitempty"`

	// StubId Stub identifier
	StubId *uuid.UUID `json:"stubId,omitempty"`

	// Timestamp When the call was received (RFC 3339).
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Dashboard Overview and runtime info in a single payload.
type Dashboard struct {
	// AppName Application name reported by the binary.
	AppName string `json:"appName"`

	// Compiler Go compiler used for the build.
	Compiler string `json:"compiler"`

	// CoveredMethods Number of gRPC methods that have at least one stub
	CoveredMethods int `json:"coveredMethods,omitempty"`

	// GatewayAddr ConnectRPC + gRPC-web listen address
	GatewayAddr string `json:"gatewayAddr,omitempty"`

	// GoVersion Go version the binary was built with.
	GoVersion string `json:"goVersion"`

	// Goarch CPU architecture the binary targets.
	Goarch string `json:"goarch"`

	// Goos Operating system the binary targets.
	Goos string `json:"goos"`

	// GrpcAddr Native gRPC listen address
	GrpcAddr string `json:"grpcAddr,omitempty"`

	// HistoryEnabled Whether call history recording is on (`HISTORY_ENABLED`).
	HistoryEnabled bool `json:"historyEnabled"`

	// HistoryErrors Recorded calls that ended in a gRPC error.
	HistoryErrors int `json:"historyErrors"`

	// HttpAddr Admin REST API + UI listen address
	HttpAddr string `json:"httpAddr,omitempty"`

	// NumCPU CPUs visible to the process.
	NumCPU int `json:"numCPU"`

	// Ready Whether the server has finished loading and is answering calls.
	Ready bool `json:"ready"`

	// RuntimeDescriptors Descriptors uploaded over REST since startup.
	RuntimeDescriptors int `json:"runtimeDescriptors"`

	// StartedAt When the process started (RFC 3339).
	StartedAt time.Time `json:"startedAt"`

	// TotalHistory Calls recorded in history.
	TotalHistory int `json:"totalHistory"`

	// TotalMethods Total number of gRPC methods across all services
	TotalMethods int `json:"totalMethods,omitempty"`

	// TotalServices Services currently registered, from every descriptor source.
	TotalServices int `json:"totalServices"`

	// TotalSessions Sessions currently known to the server.
	TotalSessions int `json:"totalSessions"`

	// TotalStubs Stubs currently in storage.
	TotalStubs int `json:"totalStubs"`

	// UnusedStubs Stubs never matched since startup.
	UnusedStubs int `json:"unusedStubs"`

	// UptimeSeconds Seconds since startup.
	UptimeSeconds int `json:"uptimeSeconds"`

	// UsedStubs Stubs matched at least once since startup.
	UsedStubs int `json:"usedStubs"`

	// Version GripMock version.
	Version string `json:"version"`
}

// DashboardInfo Build and runtime information about this instance.
type DashboardInfo struct {
	// AppName Application name reported by the binary.
	AppName string `json:"appName"`

	// Compiler Go compiler used for the build.
	Compiler string `json:"compiler"`

	// GoVersion Go version the binary was built with.
	GoVersion string `json:"goVersion"`

	// Goarch CPU architecture the binary targets.
	Goarch string `json:"goarch"`

	// Goos Operating system the binary targets.
	Goos string `json:"goos"`

	// HistoryEnabled Whether call history recording is on (`HISTORY_ENABLED`).
	HistoryEnabled bool `json:"historyEnabled"`

	// NumCPU CPUs visible to the process.
	NumCPU int `json:"numCPU"`

	// Ready Whether the server has finished loading and is answering calls.
	Ready bool `json:"ready"`

	// RuntimeDescriptors Descriptors uploaded over REST since startup.
	RuntimeDescriptors int `json:"runtimeDescriptors"`

	// StartedAt When the process started (RFC 3339).
	StartedAt time.Time `json:"startedAt"`

	// TotalServices Services currently registered, from every descriptor source.
	TotalServices int `json:"totalServices"`

	// TotalSessions Sessions currently known to the server.
	TotalSessions int `json:"totalSessions"`

	// TotalStubs Stubs currently in storage.
	TotalStubs int `json:"totalStubs"`

	// UptimeSeconds Seconds since startup.
	UptimeSeconds int `json:"uptimeSeconds"`

	// Version GripMock version.
	Version string `json:"version"`
}

// DashboardOverview Aggregate counters shown on the dashboard.
type DashboardOverview struct {
	// CoveredMethods Number of gRPC methods that have at least one stub
	CoveredMethods int `json:"coveredMethods,omitempty"`

	// GatewayAddr ConnectRPC + gRPC-web listen address
	GatewayAddr string `json:"gatewayAddr,omitempty"`

	// GrpcAddr Native gRPC listen address
	GrpcAddr string `json:"grpcAddr,omitempty"`

	// HistoryErrors Recorded calls that ended in a gRPC error.
	HistoryErrors int `json:"historyErrors"`

	// HttpAddr Admin REST API + UI listen address
	HttpAddr string `json:"httpAddr,omitempty"`

	// RuntimeDescriptors Descriptors uploaded over REST since startup.
	RuntimeDescriptors int `json:"runtimeDescriptors"`

	// TotalHistory Calls recorded in history.
	TotalHistory int `json:"totalHistory"`

	// TotalMethods Total number of gRPC methods across all services
	TotalMethods int `json:"totalMethods,omitempty"`

	// TotalServices Services currently registered, from every descriptor source.
	TotalServices int `json:"totalServices"`

	// TotalSessions Sessions currently known to the server.
	TotalSessions int `json:"totalSessions"`

	// TotalStubs Stubs currently in storage.
	TotalStubs int `json:"totalStubs"`

	// UnusedStubs Stubs never matched since startup.
	UnusedStubs int `json:"unusedStubs"`

	// UsedStubs Stubs matched at least once since startup.
	UsedStubs int `json:"usedStubs"`
}

// DescriptorServiceIDs Service IDs registered from descriptors uploaded over REST.
type DescriptorServiceIDs struct {
	// ServiceIDs Service IDs added via POST /descriptors
	ServiceIDs []string `json:"serviceIDs"`
}

// HistoryList A page of recorded calls, newest first.
type HistoryList = []CallRecord

// ID Stub identifier (UUID).
//
// Example: 51c50050-ec27-4dae-a583-a32ca71a1dd5
type ID = uuid.UUID

// InspectCandidate A stub the server considered, with the verdict at each stage.
type InspectCandidate struct {
	// Events Per-stage verdicts for this candidate.
	Events []InspectCandidateEvent `json:"events"`

	// ExcludedBy Reasons this candidate was ruled out; empty when it survived.
	ExcludedBy []string `json:"excludedBy"`

	// HeadersMatched Whether the stub `headers` matched the request metadata.
	HeadersMatched bool `json:"headersMatched"`

	// Id Stub UUID.
	Id string `json:"id"`

	// InputMatched Whether the stub `input` matched the request body.
	InputMatched bool `json:"inputMatched"`

	// Matched True for the single stub that won.
	Matched bool `json:"matched"`

	// Method Method the stub answers.
	Method string `json:"method"`

	// Priority The stub `priority` value.
	Priority int `json:"priority"`

	// Score Match rank plus `priority × 10`. Breaks ties between equally specific stubs.
	Score float64 `json:"score"`

	// Service Service the stub answers.
	Service string `json:"service"`

	// Session Session the stub belongs to; empty means global.
	Session string `json:"session"`

	// Specificity How narrowly the stub describes the request. Compared first when picking a winner.
	Specificity int `json:"specificity"`

	// Times Effective match limit; `0` means unlimited.
	Times int `json:"times"`

	// Used How many times the stub has already matched in this session.
	Used int `json:"used"`

	// VisibleBySession False when the stub belongs to a different session.
	VisibleBySession bool `json:"visibleBySession"`

	// WithinTimes False when the stub is exhausted by its `times` limit.
	WithinTimes bool `json:"withinTimes"`
}

// InspectCandidateEvent What happened to one candidate at one stage.
type InspectCandidateEvent struct {
	// Reason Why, when the candidate was dropped.
	Reason *string `json:"reason,omitempty"`

	// Result Whether the candidate passed the stage, was dropped, or was selected.
	Result string `json:"result"`

	// Stage Stage the event belongs to.
	Stage string `json:"stage"`
}

// InspectReport Why a request matched — or did not. Stages show how the candidate set narrowed.
type InspectReport struct {
	// Candidates Every stub considered, with its verdict.
	Candidates []InspectCandidate `json:"candidates"`

	// Error Why the request could not be resolved.
	Error string `json:"error"`

	// FallbackToMethod True when no stub matched the input and the search widened to any stub on the method.
	FallbackToMethod bool `json:"fallbackToMethod"`

	// MatchedStubId UUID of the winning stub, absent when nothing matched.
	MatchedStubId string `json:"matchedStubId"`

	// Method Method that was inspected.
	Method string `json:"method"`

	// Service Service that was inspected.
	Service string `json:"service"`

	// Session Session the request was resolved against.
	Session string `json:"session"`

	// SimilarStubId Closest non-matching stub, offered as a hint when nothing matched.
	SimilarStubId string `json:"similarStubId"`

	// Stages How the candidate set narrowed, step by step.
	Stages []InspectStage `json:"stages"`
}

// InspectRequest A request to explain: the server reports every stub it considered and why each was kept or dropped.
type InspectRequest struct {
	// Headers Request metadata, matched against stub `headers`.
	Headers map[string]any `json:"headers,omitempty"`

	// Id Stub identifier (UUID).
	//
	// Example: 51c50050-ec27-4dae-a583-a32ca71a1dd5
	Id *ID `json:"id,omitempty"`

	// Input Request body, matched against stub `input`.
	Input []map[string]any `json:"input,omitempty"`

	// Method gRPC method name.
	Method string `json:"method"`

	// Service Fully qualified gRPC service name.
	Service string `json:"service"`

	// Session Session to resolve against; empty means the global scope.
	Session *string `json:"session,omitempty"`
}

// InspectStage One filtering step, with how many candidates entered and survived it.
type InspectStage struct {
	// After Candidates surviving the step.
	After int `json:"after"`

	// Before Candidates entering the step.
	Before int `json:"before"`

	// Name Filter applied at this step: service/method, session, times, headers, input, or the method fallback.
	Name string `json:"name"`

	// Removed Candidates dropped by the step (`before` minus `after`).
	Removed int `json:"removed"`
}

// ListID A list of stub UUIDs.
type ListID = []ID

// MessageOK Generic acknowledgement.
type MessageOK struct {
	// Message Human-readable result of the operation.
	Message string `json:"message"`

	// Time Server time when the response was produced (RFC 3339).
	Time time.Time `json:"time"`
}

// Method A method of a gRPC service.
type Method struct {
	// ClientStreaming Indicates client-side streaming method
	ClientStreaming bool `json:"clientStreaming,omitempty"`

	// Id Method name, used as the path segment in `/methods/{methodID}`.
	Id string `json:"id"`

	// MethodType gRPC method interaction type
	MethodType MethodMethodType `json:"methodType"`

	// Name Method name as declared in the proto file.
	Name string `json:"name"`

	// RequestSchema Shape of a proto message, as GripMock resolved it from the descriptor.
	RequestSchema *ProtoMessageSchema `json:"requestSchema,omitempty"`

	// RequestType Fully-qualified protobuf request message type
	RequestType *string `json:"requestType,omitempty"`

	// ResponseSchema Shape of a proto message, as GripMock resolved it from the descriptor.
	ResponseSchema *ProtoMessageSchema `json:"responseSchema,omitempty"`

	// ResponseType Fully-qualified protobuf response message type
	ResponseType *string `json:"responseType,omitempty"`

	// ServerStreaming Indicates server-side streaming method
	ServerStreaming bool `json:"serverStreaming,omitempty"`
}

// MethodMethodType gRPC method interaction type
type MethodMethodType string

// ProtoFieldSchema A single field of a proto message.
type ProtoFieldSchema struct {
	// Cardinality Whether the field is optional, required or repeated.
	Cardinality ProtoFieldSchemaCardinality `json:"cardinality"`

	// EnumValues Allowed value names when `kind` is `enum`.
	EnumValues *[]string `json:"enumValues,omitempty"`

	// JsonName Field name in protojson output (camelCase).
	JsonName string `json:"jsonName"`

	// Kind Proto kind, for example `string`, `int32`, `message`, `enum`.
	Kind string `json:"kind"`

	// Map True when the field is a proto map.
	Map bool `json:"map,omitempty"`

	// MapKeyKind Kind of the map key, when `map` is true.
	MapKeyKind *string `json:"mapKeyKind,omitempty"`

	// MapValueKind Kind of the map value, when `map` is true.
	MapValueKind *string `json:"mapValueKind,omitempty"`

	// MapValueMessage Shape of a proto message, as GripMock resolved it from the descriptor.
	MapValueMessage *ProtoMessageSchema `json:"mapValueMessage,omitempty"`

	// MapValueTypeName Fully qualified type name of the map value, when it is a message or enum.
	MapValueTypeName *string `json:"mapValueTypeName,omitempty"`

	// Message Shape of a proto message, as GripMock resolved it from the descriptor.
	Message *ProtoMessageSchema `json:"message,omitempty"`

	// Name Field name as declared in the proto file (snake_case).
	Name string `json:"name"`

	// Number Field number from the proto definition.
	Number int `json:"number"`

	// Oneof Oneof group name if field belongs to oneof
	Oneof *string `json:"oneof,omitempty"`

	// TypeName Referenced protobuf type for message/enum fields
	TypeName *string `json:"typeName,omitempty"`
}

// ProtoFieldSchemaCardinality Whether the field is optional, required or repeated.
type ProtoFieldSchemaCardinality string

// ProtoMessageSchema Shape of a proto message, as GripMock resolved it from the descriptor.
type ProtoMessageSchema struct {
	// Fields Fields declared on the message.
	Fields []ProtoFieldSchema `json:"fields"`

	// RecursiveRef True when schema expansion stopped due to recursive reference
	RecursiveRef bool `json:"recursiveRef,omitempty"`

	// TypeName Fully-qualified protobuf message type name
	TypeName string `json:"typeName"`
}

// SearchRequest A synthetic gRPC request. The server resolves it against the loaded stubs and returns the output of the winning stub, without performing the call.
type SearchRequest struct {
	// Data Request body to match against stub `input`.
	Data any `json:"data"`

	// Headers Request metadata to match against stub `headers`.
	Headers map[string]string `json:"headers,omitempty"`

	// Id Stub identifier (UUID).
	//
	// Example: 51c50050-ec27-4dae-a583-a32ca71a1dd5
	Id *ID `json:"id,omitempty"`

	// Method gRPC method name.
	//
	// Example: SayHello
	Method string `json:"method"`

	// Service Fully qualified gRPC service name.
	//
	// Example: Gripmock
	Service string `json:"service"`
}

// SearchResponse Output of the stub that won the match.
type SearchResponse struct {
	// Code gRPC status code.
	//
	// Example: 3
	Code codes.Code `json:"code,omitempty"`

	// Data Response body of the matched stub.
	Data any `json:"data"`

	// Error gRPC status message, empty when the stub returns data.
	//
	// Example: Message not found
	Error string `json:"error"`

	// Headers Response metadata of the matched stub.
	Headers map[string]string `json:"headers,omitempty"`
}

// Service A gRPC service GripMock can serve.
type Service struct {
	// Id Fully qualified service name, used as the path segment in `/services/{serviceID}`.
	Id string `json:"id"`

	// Methods Methods the service exposes.
	Methods []Method `json:"methods"`

	// Name Service name without the package prefix.
	Name string `json:"name"`

	// Package Proto package the service is declared in.
	Package string `json:"package"`
}

// Sessions Session IDs currently known to the server.
type Sessions struct {
	// Sessions Known session IDs.
	Sessions []string `json:"sessions"`
}

// Stub A single stub: which method it answers, which requests it accepts, and what it returns.
type Stub struct {
	// Effects Side effects applied after successful stub match
	Effects []StubEffect `json:"effects,omitempty"`

	// Headers Matchers applied to gRPC request metadata. Header names are case-insensitive. All blocks present are AND-ed; an omitted or empty block always passes.
	Headers StubHeaders `json:"headers,omitempty"`

	// Id Stub identifier (UUID).
	//
	// Example: 51c50050-ec27-4dae-a583-a32ca71a1dd5
	Id *ID `json:"id,omitempty"`

	// Input Matchers applied to the request body. All blocks present are AND-ed; an omitted or empty block always passes, so a stub with every block empty matches any request.
	Input StubInput `json:"input"`

	// Inputs Per-message matchers for client and bidirectional streaming. With one element it is a broadcast pattern that every message must match; with several, element N is matched against the Nth message and the counts must be equal. Mutually exclusive with `input` — a stub with both is rejected. For OR semantics use `input.anyOf`.
	Inputs []StubInput `json:"inputs,omitempty"`

	// Method gRPC method name, without the service prefix.
	//
	// Example: SayHello
	Method string `json:"method"`

	// Options Optional behavior settings for a stub
	Options *StubOptions `json:"options,omitempty,omitzero"`

	// Output What the stub returns. Over this API exactly one side must be set: either the unary side (`data`, `dataTemplate`, `error`, `code`, `details`) or the stream side (`stream`, `streamTemplate`). Static and templated forms on the same side are mutually exclusive.
	Output StubOutput `json:"output"`

	// Priority Tie-breaker among equally specific stubs; higher wins. Specificity is compared first, so an `equals` stub still beats a `contains` stub with a higher priority.
	Priority int `json:"priority,omitempty"`

	// Service Fully qualified gRPC service name.
	//
	// Example: Gripmock
	Service string `json:"service"`

	// Source Source of the stub (file, rest, mcp, proxy)
	Source *string `json:"source,omitempty,omitzero"`

	// Used Response-only — whether the stub has matched at least once. Ignored on input.
	Used bool `json:"used,omitempty"`
}

// StubEffect Side effect applied after this stub matches — used to build multi-step flows where one call arms the next.
type StubEffect struct {
	// Action `upsert` creates or replaces a stub, `delete` removes one.
	Action StubEffectAction `json:"action"`

	// Id Target stub UUID for `delete`. May be a template that renders to a UUID.
	Id string `json:"id,omitempty"`

	// Stub Stub payload for `upsert`, validated after template rendering.
	Stub map[string]any `json:"stub,omitempty"`
}

// StubEffectAction `upsert` creates or replaces a stub, `delete` removes one.
type StubEffectAction string

// StubHeaders Matchers applied to gRPC request metadata. Header names are case-insensitive. All blocks present are AND-ed; an omitted or empty block always passes.
type StubHeaders struct {
	// AnyOf Alternative header matchers (OR). The stub matches when the blocks above pass AND at least one element here passes.
	AnyOf []StubHeadersAnyOfElement `json:"anyOf,omitempty"`

	// Contains Subset match. The request must carry at least these header names; values match on substring.
	Contains map[string]string `json:"contains,omitempty"`

	// Equals Exact match on header values (multiple values are joined with `;`).
	Equals map[string]string `json:"equals,omitempty"`

	// Glob Glob match on header values, using Go `path.Match`.
	Glob map[string]string `json:"glob,omitempty"`

	// Matches Regex match on header values.
	Matches map[string]string `json:"matches,omitempty"`
}

// StubHeadersAnyOfElement One alternative of a header `anyOf`. Its own blocks are AND-ed together.
type StubHeadersAnyOfElement struct {
	// Contains Subset match. The request must carry at least these header names; values match on substring.
	Contains map[string]string `json:"contains,omitempty"`

	// Equals Exact match on header values (multiple values are joined with `;`).
	Equals map[string]string `json:"equals,omitempty"`

	// Glob Glob match on header values, using Go `path.Match`.
	Glob map[string]string `json:"glob,omitempty"`

	// Matches Regex match on header values.
	Matches map[string]string `json:"matches,omitempty"`
}

// StubInput Matchers applied to the request body. All blocks present are AND-ed; an omitted or empty block always passes, so a stub with every block empty matches any request.
type StubInput struct {
	// AnyOf Alternative matchers (OR). The stub matches when the blocks above pass AND at least one element here passes. Depth is exactly one — an element cannot itself contain `anyOf`.
	AnyOf []StubInputAnyOfElement `json:"anyOf,omitempty"`

	// Contains Subset match. The request must carry at least these fields. Strings match on substring, arrays on containment, nested objects recursively. Extra fields in the request are ignored.
	Contains map[string]any `json:"contains,omitempty"`

	// Equals Exact match. Every listed field must be present in the request with exactly this value, case-sensitive. Arrays compare in order unless `ignoreArrayOrder` is set.
	Equals map[string]any `json:"equals,omitempty"`

	// Glob Glob match. Each leaf value is a shell-style pattern (`*`, `?`, `[...]`) evaluated with Go `path.Match`; `*` does not cross `/`.
	Glob map[string]any `json:"glob,omitempty"`

	// IgnoreArrayOrder Compare arrays as sets rather than ordered sequences. Applies to this matcher block only — it is not inherited by `anyOf` elements.
	IgnoreArrayOrder bool `json:"ignoreArrayOrder,omitempty"`

	// Matches Regex match. Each leaf value is a Go regular expression applied to the corresponding request value.
	Matches map[string]any `json:"matches,omitempty"`
}

// StubInputAnyOfElement One alternative of an `anyOf`. Its own blocks are AND-ed together.
type StubInputAnyOfElement struct {
	// Contains Subset match. The request must carry at least these fields. Strings match on substring, arrays on containment, nested objects recursively. Extra fields in the request are ignored.
	Contains map[string]any `json:"contains,omitempty"`

	// Equals Exact match. Every listed field must be present in the request with exactly this value, case-sensitive. Arrays compare in order unless `ignoreArrayOrder` is set.
	Equals map[string]any `json:"equals,omitempty"`

	// Glob Glob match. Each leaf value is a shell-style pattern (`*`, `?`, `[...]`) evaluated with Go `path.Match`; `*` does not cross `/`.
	Glob map[string]any `json:"glob,omitempty"`

	// IgnoreArrayOrder Compare arrays as sets rather than ordered sequences. Applies to this matcher block only — it is not inherited by `anyOf` elements.
	IgnoreArrayOrder bool `json:"ignoreArrayOrder,omitempty"`

	// Matches Regex match. Each leaf value is a Go regular expression applied to the corresponding request value.
	Matches map[string]any `json:"matches,omitempty"`
}

// StubList A list of stubs.
type StubList = []Stub

// StubOptions Optional behavior settings for a stub
type StubOptions struct {
	// Times Maximum number of matches; `0` means unlimited. Once the limit is reached the stub is exhausted and stops matching, though it stays in storage.
	Times int `json:"times,omitempty"`
}

// StubOutput What the stub returns. Over this API exactly one side must be set: either the unary side (`data`, `dataTemplate`, `error`, `code`, `details`) or the stream side (`stream`, `streamTemplate`). Static and templated forms on the same side are mutually exclusive.
type StubOutput struct {
	// Code gRPC status code; `0` (OK) is the default.
	//
	// Example: 3
	Code codes.Code `json:"code,omitempty"`

	// Data Response body for unary and client-streaming calls. Usually an object matching the proto message; may be a scalar when the method returns a well-known type directly.
	Data any `json:"data,omitempty"`

	// DataTemplate Runtime Go template that renders a complete YAML or JSON response body for unary and client-streaming calls. Cannot be combined with `data` or stream-side output.
	DataTemplate string `json:"dataTemplate,omitempty"`

	// Delay Delay before sending the response
	//
	// Example: 1s
	Delay gptypes.Duration `json:"delay,omitempty,omitzero"`

	// Details gRPC status details packed into google.protobuf.Any (each item must contain type URL in `type`)
	Details []StubOutput_Details_Item `json:"details,omitempty"`

	// Error gRPC status message. Returned instead of `data`, and counts as the unary side of the data/stream choice.
	//
	// Example: Message not found
	Error string `json:"error,omitempty"`

	// Headers Response metadata.
	Headers map[string]string `json:"headers,omitempty"`

	// Stream Response messages for server and bidirectional streaming, sent in order. Cannot be combined with `data`, `error`, `code` or `details` on this endpoint.
	Stream []any `json:"stream,omitempty"`

	// StreamTemplate Runtime Go template that must render a YAML or JSON array of messages for server and bidirectional streaming calls. Cannot be combined with `stream` or data-side output.
	StreamTemplate string `json:"streamTemplate,omitempty"`

	// Trailers Trailing metadata, sent after the last message with the status. Independent of `headers`: the same key may appear in both, and each is delivered on its own channel.
	Trailers map[string]string `json:"trailers,omitempty"`
}

// StubOutput_Details_Item defines model for StubOutput.details.Item.
type StubOutput_Details_Item struct {
	// Type Full Any type URL (for example, type.googleapis.com/google.rpc.ErrorInfo)
	Type                 string         `json:"type"`
	AdditionalProperties map[string]any `json:"-"`
}

// VerifyError Reported when the recorded count differs from the expectation.
type VerifyError struct {
	// Actual Count actually recorded.
	Actual *int `json:"actual,omitempty"`

	// Expected Count the caller asked for.
	Expected *int `json:"expected,omitempty"`

	// Message Human-readable summary of the mismatch.
	Message *string `json:"message,omitempty"`
}

// VerifyRequest Expected number of calls to one method.
type VerifyRequest struct {
	// ExpectedCount Number of calls the method must have received.
	ExpectedCount int `json:"expectedCount"`

	// Method gRPC method name.
	Method string `json:"method"`

	// Service Fully qualified gRPC service name.
	Service string `json:"service"`
}

// ListHistoryParams defines parameters for ListHistory.
type ListHistoryParams struct {
	// Limit Return at most N most-recent records
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the N newest records (page backward through older calls)
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Service Keep only calls to this fully qualified service name.
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// Method Keep only calls to this method name.
	Method *string `form:"method,omitempty" json:"method,omitempty"`

	// Error When true, return only calls that ended with a gRPC error
	Error *bool `form:"error,omitempty" json:"error,omitempty"`
}

// ListStubsParams defines parameters for ListStubs.
type ListStubsParams struct {
	// Source Filter by source (file, rest, mcp, proxy)
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Service Filter by service name (exact match)
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// Method Filter by method name (exact match)
	Method *string `form:"method,omitempty" json:"method,omitempty"`

	// Session Filter by session ID (empty means global stubs)
	Session *string `form:"session,omitempty" json:"session,omitempty"`

	// Q Case-insensitive substring search over service, method and stub ID
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Matcher Filter by matcher kind(s) present on the stub input. Comma-separated for OR semantics (e.g. "glob,anyOf"). Valid kinds: equals, contains, matches, glob, anyOf.
	Matcher *string `form:"matcher,omitempty" json:"matcher,omitempty"`

	// Limit Maximum number of returned stubs
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of stubs to skip before returning results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Sort order for result list
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// AddStubJSONBody defines parameters for AddStub.
type AddStubJSONBody struct {
	union json.RawMessage
}

// AddStub200JSONResponseBody defines parameters for AddStub.
type AddStub200JSONResponseBody struct {
	union json.RawMessage
}

// ValidateStubJSONBody defines parameters for ValidateStub.
type ValidateStubJSONBody struct {
	union json.RawMessage
}

// ValidateStub200JSONResponseBody defines parameters for ValidateStub.
type ValidateStub200JSONResponseBody struct {
	union json.RawMessage
}

// AddStubJSONRequestBody defines body for AddStub for application/json ContentType.
type AddStubJSONRequestBody AddStubJSONBody

// BatchStubsDeleteJSONRequestBody defines body for BatchStubsDelete for application/json ContentType.
type BatchStubsDeleteJSONRequestBody = ListID

// InspectStubsJSONRequestBody defines body for InspectStubs for application/json ContentType.
type InspectStubsJSONRequestBody = InspectRequest

// SearchStubsJSONRequestBody defines body for SearchStubs for application/json ContentType.
type SearchStubsJSONRequestBody = SearchRequest

// ValidateStubJSONRequestBody defines body for ValidateStub for application/json ContentType.
type ValidateStubJSONRequestBody ValidateStubJSONBody

// VerifyCallsJSONRequestBody defines body for VerifyCalls for application/json ContentType.
type VerifyCallsJSONRequestBody = VerifyRequest

// Getter for additional properties for StubOutput_Details_Item. Returns the specified
// element and whether it was found
func (a StubOutput_Details_Item) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StubOutput_Details_Item
func (a *StubOutput_Details_Item) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a *StubOutput_Details_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a StubOutput_Details_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsStubList returns the union data inside the AddStubJSONBody as a StubList
func (t AddStubJSONBody) AsStubList() (StubList, error) {
	var body StubList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStubList overwrites any union data inside the AddStubJSONBody as the provided StubList
func (t *AddStubJSONBody) FromStubList(v StubList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStubList performs a merge with any union data inside the AddStubJSONBody, using the provided StubList
func (t *AddStubJSONBody) MergeStubList(v StubList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStub returns the union data inside the AddStubJSONBody as a Stub
func (t AddStubJSONBody) AsStub() (Stub, error) {
	var body Stub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStub overwrites any union data inside the AddStubJSONBody as the provided Stub
func (t *AddStubJSONBody) FromStub(v Stub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStub performs a merge with any union data inside the AddStubJSONBody, using the provided Stub
func (t *AddStubJSONBody) MergeStub(v Stub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AddStubJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AddStubJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsListID returns the union data inside the AddStub200JSONResponseBody as a ListID
func (t AddStub200JSONResponseBody) AsListID() (ListID, error) {
	var body ListID
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListID overwrites any union data inside the AddStub200JSONResponseBody as the provided ListID
func (t *AddStub200JSONResponseBody) FromListID(v ListID) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListID performs a merge with any union data inside the AddStub200JSONResponseBody, using the provided ListID
func (t *AddStub200JSONResponseBody) MergeListID(v ListID) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AddStub200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AddStub200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStubList returns the union data inside the ValidateStubJSONBody as a StubList
func (t ValidateStubJSONBody) AsStubList() (StubList, error) {
	var body StubList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStubList overwrites any union data inside the ValidateStubJSONBody as the provided StubList
func (t *ValidateStubJSONBody) FromStubList(v StubList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStubList performs a merge with any union data inside the ValidateStubJSONBody, using the provided StubList
func (t *ValidateStubJSONBody) MergeStubList(v StubList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStub returns the union data inside the ValidateStubJSONBody as a Stub
func (t ValidateStubJSONBody) AsStub() (Stub, error) {
	var body Stub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStub overwrites any union data inside the ValidateStubJSONBody as the provided Stub
func (t *ValidateStubJSONBody) FromStub(v Stub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStub performs a merge with any union data inside the ValidateStubJSONBody, using the provided Stub
func (t *ValidateStubJSONBody) MergeStub(v Stub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidateStubJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidateStubJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStubList returns the union data inside the ValidateStub200JSONResponseBody as a StubList
func (t ValidateStub200JSONResponseBody) AsStubList() (StubList, error) {
	var body StubList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStubList overwrites any union data inside the ValidateStub200JSONResponseBody as the provided StubList
func (t *ValidateStub200JSONResponseBody) FromStubList(v StubList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStubList performs a merge with any union data inside the ValidateStub200JSONResponseBody, using the provided StubList
func (t *ValidateStub200JSONResponseBody) MergeStubList(v StubList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidateStub200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidateStub200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Dashboard Dashboard aggregate payload
	// (GET /dashboard)
	Dashboard(w http.ResponseWriter, r *http.Request)
	// DashboardInfo Dashboard runtime and build info
	// (GET /dashboard/info)
	DashboardInfo(w http.ResponseWriter, r *http.Request)
	// DashboardOverview Dashboard overview metrics
	// (GET /dashboard/overview)
	DashboardOverview(w http.ResponseWriter, r *http.Request)
	// ListDescriptors List service IDs from REST-added descriptors
	// (GET /descriptors)
	ListDescriptors(w http.ResponseWriter, r *http.Request)
	// AddDescriptors Upload FileDescriptorSet
	// (POST /descriptors)
	AddDescriptors(w http.ResponseWriter, r *http.Request)
	// Liveness Liveness check
	// (GET /health/liveness)
	Liveness(w http.ResponseWriter, r *http.Request)
	// Readiness Readiness check
	// (GET /health/readiness)
	Readiness(w http.ResponseWriter, r *http.Request)
	// ListHistory Get call history
	// (GET /history)
	ListHistory(w http.ResponseWriter, r *http.Request, params ListHistoryParams)
	// ServicesList Services
	// (GET /services)
	ServicesList(w http.ResponseWriter, r *http.Request)
	// DeleteService Remove service
	// (DELETE /services/{serviceID})
	DeleteService(w http.ResponseWriter, r *http.Request, serviceID string)
	// ServiceGet Service details
	// (GET /services/{serviceID})
	ServiceGet(w http.ResponseWriter, r *http.Request, serviceID string)
	// ServiceMethodsList Service methods
	// (GET /services/{serviceID}/methods)
	ServiceMethodsList(w http.ResponseWriter, r *http.Request, serviceID string)
	// ServiceMethodGet Service method details
	// (GET /services/{serviceID}/methods/{methodID})
	ServiceMethodGet(w http.ResponseWriter, r *http.Request, serviceID string, methodID string)
	// SessionsList Session options
	// (GET /sessions)
	SessionsList(w http.ResponseWriter, r *http.Request)
	// PurgeStubs Remove all stubs
	// (DELETE /stubs)
	PurgeStubs(w http.ResponseWriter, r *http.Request)
	// ListStubs Getting a list of stubs
	// (GET /stubs)
	ListStubs(w http.ResponseWriter, r *http.Request, params ListStubsParams)
	// AddStub Add a new stub to the store
	// (POST /stubs)
	AddStub(w http.ResponseWriter, r *http.Request)
	// BatchStubsDelete Deletes a batch of stubs by IDs
	// (POST /stubs/batchDelete)
	BatchStubsDelete(w http.ResponseWriter, r *http.Request)
	// InspectStubs Inspect stub matching decision path
	// (POST /stubs/inspect)
	InspectStubs(w http.ResponseWriter, r *http.Request)
	// SearchStubs Stub storage search
	// (POST /stubs/search)
	SearchStubs(w http.ResponseWriter, r *http.Request)
	// ListUnusedStubs Getting a list of unused stubs
	// (GET /stubs/unused)
	ListUnusedStubs(w http.ResponseWriter, r *http.Request)
	// ListUsedStubs Getting a list of used stubs
	// (GET /stubs/used)
	ListUsedStubs(w http.ResponseWriter, r *http.Request)
	// ValidateStub Validate a stub payload without persisting
	// (POST /stubs/validate)
	ValidateStub(w http.ResponseWriter, r *http.Request)
	// DeleteStubByID Deletes stub by ID
	// (DELETE /stubs/{uuid})
	DeleteStubByID(w http.ResponseWriter, r *http.Request, uuid ID)
	// FindByID Get Stub by ID
	// (GET /stubs/{uuid})
	FindByID(w http.ResponseWriter, r *http.Request, uuid ID)
	// VerifyCalls Verify call counts
	// (POST /verify)
	VerifyCalls(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Dashboard operation middleware
func (siw *ServerInterfaceWrapper) Dashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Dashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardInfo operation middleware
func (siw *ServerInterfaceWrapper) DashboardInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardOverview operation middleware
func (siw *ServerInterfaceWrapper) DashboardOverview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardOverview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDescriptors operation middleware
func (siw *ServerInterfaceWrapper) ListDescriptors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDescriptors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddDescriptors operation middleware
func (siw *ServerInterfaceWrapper) AddDescriptors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDescriptors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Liveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHistory operation middleware
func (siw *ServerInterfaceWrapper) ListHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "service" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service", r.URL.Query(), &params.Service, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "service"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", r.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServicesList operation middleware
func (siw *ServerInterfaceWrapper) ServicesList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServicesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceGet(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceMethodsList operation middleware
func (siw *ServerInterfaceWrapper) ServiceMethodsList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceMethodsList(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceMethodGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceMethodGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	// ------------- Path parameter "methodID" -------------
	var methodID string

	err = runtime.BindStyledParameterWithOptions("simple", "methodID", mux.Vars(r)["methodID"], &methodID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "methodID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceMethodGet(w, r, serviceID, methodID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionsList operation middleware
func (siw *ServerInterfaceWrapper) SessionsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeStubs operation middleware
func (siw *ServerInterfaceWrapper) PurgeStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStubs operation middleware
func (siw *ServerInterfaceWrapper) ListStubs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStubsParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "service" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service", r.URL.Query(), &params.Service, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "service"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", r.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "session" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "session", r.URL.Query(), &params.Session, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "session"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "matcher" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "matcher", r.URL.Query(), &params.Matcher, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "matcher"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "matcher", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStubs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddStub operation middleware
func (siw *ServerInterfaceWrapper) AddStub(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddStub(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchStubsDelete operation middleware
func (siw *ServerInterfaceWrapper) BatchStubsDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchStubsDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectStubs operation middleware
func (siw *ServerInterfaceWrapper) InspectStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchStubs operation middleware
func (siw *ServerInterfaceWrapper) SearchStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUnusedStubs operation middleware
func (siw *ServerInterfaceWrapper) ListUnusedStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUnusedStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsedStubs operation middleware
func (siw *ServerInterfaceWrapper) ListUsedStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsedStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateStub operation middleware
func (siw *ServerInterfaceWrapper) ValidateStub(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateStub(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStubByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteStubByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uuid" -------------
	var uuid ID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", mux.Vars(r)["uuid"], &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStubByID(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindByID operation middleware
func (siw *ServerInterfaceWrapper) FindByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uuid" -------------
	var uuid ID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", mux.Vars(r)["uuid"], &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindByID(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyCalls operation middleware
func (siw *ServerInterfaceWrapper) VerifyCalls(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyCalls(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/health/liveness", wrapper.Liveness).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/health/readiness", wrapper.Readiness).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/dashboard", wrapper.Dashboard).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/dashboard/overview", wrapper.DashboardOverview).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/dashboard/info", wrapper.DashboardInfo).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/sessions", wrapper.SessionsList).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/services", wrapper.ServicesList).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/services/{serviceID}/methods", wrapper.ServiceMethodsList).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/services/{serviceID}/methods/{methodID}", wrapper.ServiceMethodGet).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/services/{serviceID}", wrapper.DeleteService).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/services/{serviceID}", wrapper.ServiceGet).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/stubs/used", wrapper.ListUsedStubs).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/stubs/unused", wrapper.ListUnusedStubs).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.PurgeStubs).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.ListStubs).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.AddStub).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/stubs/batchDelete", wrapper.BatchStubsDelete).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/stubs/validate", wrapper.ValidateStub).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/stubs/{uuid}", wrapper.DeleteStubByID).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/stubs/{uuid}", wrapper.FindByID).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/stubs/search", wrapper.SearchStubs).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/stubs/inspect", wrapper.InspectStubs).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/history", wrapper.ListHistory).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/verify", wrapper.VerifyCalls).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/descriptors", wrapper.ListDescriptors).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/descriptors", wrapper.AddDescriptors).Methods(http.MethodPost)

	return r
}
