// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rest

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	gptypes "github.com/bavix/gripmock/v3/internal/infra/types"
	uuid "github.com/google/uuid"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	codes "google.golang.org/grpc/codes"
)

// Defines values for MethodMethodType.
const (
	BidiStreaming   MethodMethodType = "bidi_streaming"
	ClientStreaming MethodMethodType = "client_streaming"
	ServerStreaming MethodMethodType = "server_streaming"
	Unary           MethodMethodType = "unary"
)

// Valid indicates whether the value is a known member of the MethodMethodType enum.
func (e MethodMethodType) Valid() bool {
	switch e {
	case BidiStreaming:
		return true
	case ClientStreaming:
		return true
	case ServerStreaming:
		return true
	case Unary:
		return true
	default:
		return false
	}
}

// Defines values for ProtoFieldSchemaCardinality.
const (
	Optional ProtoFieldSchemaCardinality = "optional"
	Repeated ProtoFieldSchemaCardinality = "repeated"
	Required ProtoFieldSchemaCardinality = "required"
)

// Valid indicates whether the value is a known member of the ProtoFieldSchemaCardinality enum.
func (e ProtoFieldSchemaCardinality) Valid() bool {
	switch e {
	case Optional:
		return true
	case Repeated:
		return true
	case Required:
		return true
	default:
		return false
	}
}

// Defines values for StubEffectAction.
const (
	Delete StubEffectAction = "delete"
	Upsert StubEffectAction = "upsert"
)

// Valid indicates whether the value is a known member of the StubEffectAction enum.
func (e StubEffectAction) Valid() bool {
	switch e {
	case Delete:
		return true
	case Upsert:
		return true
	default:
		return false
	}
}

// AddDescriptorsResponse defines model for AddDescriptorsResponse.
type AddDescriptorsResponse struct {
	Message string `json:"message"`

	// ServiceIDs Service IDs (e.g. helloworld.Greeter) registered. Use DELETE /services/{serviceID} to remove.
	ServiceIDs []string  `json:"serviceIDs"`
	Time       time.Time `json:"time"`
}

// CallRecord defines model for CallRecord.
type CallRecord struct {
	// Code gRPC status code (e.g., 0 for OK, 5 for NotFound)
	Code   *int    `json:"code,omitempty"`
	Error  *string `json:"error,omitempty"`
	Method *string `json:"method,omitempty"`

	// Request Deprecated: use requests for streaming calls
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Request *map[string]any `json:"request,omitempty"`

	// Requests Request messages for streaming calls (client stream, bidi stream)
	Requests *[]map[string]any `json:"requests,omitempty"`

	// Response Deprecated: use responses for streaming calls
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Response *map[string]any `json:"response,omitempty"`

	// Responses Response messages for streaming calls (server stream, bidi stream)
	Responses *[]map[string]any `json:"responses,omitempty"`
	Service   *string           `json:"service,omitempty"`

	// Session Session ID (empty = global)
	Session *string `json:"session,omitempty"`

	// StubId Stub identifier
	StubId    *uuid.UUID `json:"stubId,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	AppName            string    `json:"appName"`
	Compiler           string    `json:"compiler"`
	GoVersion          string    `json:"goVersion"`
	Goarch             string    `json:"goarch"`
	Goos               string    `json:"goos"`
	HistoryEnabled     bool      `json:"historyEnabled"`
	HistoryErrors      int       `json:"historyErrors"`
	NumCPU             int       `json:"numCPU"`
	Ready              bool      `json:"ready"`
	RuntimeDescriptors int       `json:"runtimeDescriptors"`
	StartedAt          time.Time `json:"startedAt"`
	TotalHistory       int       `json:"totalHistory"`
	TotalServices      int       `json:"totalServices"`
	TotalSessions      int       `json:"totalSessions"`
	TotalStubs         int       `json:"totalStubs"`
	UnusedStubs        int       `json:"unusedStubs"`
	UptimeSeconds      int       `json:"uptimeSeconds"`
	UsedStubs          int       `json:"usedStubs"`
	Version            string    `json:"version"`
}

// DashboardInfo defines model for DashboardInfo.
type DashboardInfo struct {
	AppName            string    `json:"appName"`
	Compiler           string    `json:"compiler"`
	GoVersion          string    `json:"goVersion"`
	Goarch             string    `json:"goarch"`
	Goos               string    `json:"goos"`
	HistoryEnabled     bool      `json:"historyEnabled"`
	NumCPU             int       `json:"numCPU"`
	Ready              bool      `json:"ready"`
	RuntimeDescriptors int       `json:"runtimeDescriptors"`
	StartedAt          time.Time `json:"startedAt"`
	TotalServices      int       `json:"totalServices"`
	TotalSessions      int       `json:"totalSessions"`
	TotalStubs         int       `json:"totalStubs"`
	UptimeSeconds      int       `json:"uptimeSeconds"`
	Version            string    `json:"version"`
}

// DashboardOverview defines model for DashboardOverview.
type DashboardOverview struct {
	HistoryErrors      int `json:"historyErrors"`
	RuntimeDescriptors int `json:"runtimeDescriptors"`
	TotalHistory       int `json:"totalHistory"`
	TotalServices      int `json:"totalServices"`
	TotalSessions      int `json:"totalSessions"`
	TotalStubs         int `json:"totalStubs"`
	UnusedStubs        int `json:"unusedStubs"`
	UsedStubs          int `json:"usedStubs"`
}

// DescriptorServiceIDs defines model for DescriptorServiceIDs.
type DescriptorServiceIDs struct {
	// ServiceIDs Service IDs added via POST /descriptors
	ServiceIDs []string `json:"serviceIDs"`
}

// HistoryList defines model for HistoryList.
type HistoryList = []CallRecord

// ID defines model for ID.
type ID = uuid.UUID

// InspectCandidate defines model for InspectCandidate.
type InspectCandidate struct {
	Events           []InspectCandidateEvent `json:"events"`
	ExcludedBy       []string                `json:"excludedBy"`
	HeadersMatched   bool                    `json:"headersMatched"`
	Id               string                  `json:"id"`
	InputMatched     bool                    `json:"inputMatched"`
	Matched          bool                    `json:"matched"`
	Method           string                  `json:"method"`
	Priority         int                     `json:"priority"`
	Score            float64                 `json:"score"`
	Service          string                  `json:"service"`
	Session          string                  `json:"session"`
	Specificity      int                     `json:"specificity"`
	Times            int                     `json:"times"`
	Used             int                     `json:"used"`
	VisibleBySession bool                    `json:"visibleBySession"`
	WithinTimes      bool                    `json:"withinTimes"`
}

// InspectCandidateEvent defines model for InspectCandidateEvent.
type InspectCandidateEvent struct {
	Reason *string `json:"reason,omitempty"`
	Result string  `json:"result"`
	Stage  string  `json:"stage"`
}

// InspectReport defines model for InspectReport.
type InspectReport struct {
	Candidates       []InspectCandidate `json:"candidates"`
	Error            string             `json:"error"`
	FallbackToMethod bool               `json:"fallbackToMethod"`
	MatchedStubId    string             `json:"matchedStubId"`
	Method           string             `json:"method"`
	Service          string             `json:"service"`
	Session          string             `json:"session"`
	SimilarStubId    string             `json:"similarStubId"`
	Stages           []InspectStage     `json:"stages"`
}

// InspectRequest defines model for InspectRequest.
type InspectRequest struct {
	Headers map[string]any   `json:"headers,omitempty"`
	Id      *ID              `json:"id,omitempty"`
	Input   []map[string]any `json:"input,omitempty"`
	Method  string           `json:"method"`
	Service string           `json:"service"`
	Session *string          `json:"session,omitempty"`
}

// InspectStage defines model for InspectStage.
type InspectStage struct {
	After   int    `json:"after"`
	Before  int    `json:"before"`
	Name    string `json:"name"`
	Removed int    `json:"removed"`
}

// ListID defines model for ListID.
type ListID = []ID

// MessageOK defines model for MessageOK.
type MessageOK struct {
	Message string    `json:"message"`
	Time    time.Time `json:"time"`
}

// Method defines model for Method.
type Method struct {
	// ClientStreaming Indicates client-side streaming method
	ClientStreaming bool   `json:"clientStreaming,omitempty"`
	Id              string `json:"id"`

	// MethodType gRPC method interaction type
	MethodType    MethodMethodType    `json:"methodType"`
	Name          string              `json:"name"`
	RequestSchema *ProtoMessageSchema `json:"requestSchema,omitempty"`

	// RequestType Fully-qualified protobuf request message type
	RequestType    *string             `json:"requestType,omitempty"`
	ResponseSchema *ProtoMessageSchema `json:"responseSchema,omitempty"`

	// ResponseType Fully-qualified protobuf response message type
	ResponseType *string `json:"responseType,omitempty"`

	// ServerStreaming Indicates server-side streaming method
	ServerStreaming bool `json:"serverStreaming,omitempty"`
}

// MethodMethodType gRPC method interaction type
type MethodMethodType string

// ProtoFieldSchema defines model for ProtoFieldSchema.
type ProtoFieldSchema struct {
	Cardinality      ProtoFieldSchemaCardinality `json:"cardinality"`
	EnumValues       *[]string                   `json:"enumValues,omitempty"`
	JsonName         string                      `json:"jsonName"`
	Kind             string                      `json:"kind"`
	Map              bool                        `json:"map,omitempty"`
	MapKeyKind       *string                     `json:"mapKeyKind,omitempty"`
	MapValueKind     *string                     `json:"mapValueKind,omitempty"`
	MapValueMessage  *ProtoMessageSchema         `json:"mapValueMessage,omitempty"`
	MapValueTypeName *string                     `json:"mapValueTypeName,omitempty"`
	Message          *ProtoMessageSchema         `json:"message,omitempty"`
	Name             string                      `json:"name"`
	Number           int                         `json:"number"`

	// Oneof Oneof group name if field belongs to oneof
	Oneof *string `json:"oneof,omitempty"`

	// TypeName Referenced protobuf type for message/enum fields
	TypeName *string `json:"typeName,omitempty"`
}

// ProtoFieldSchemaCardinality defines model for ProtoFieldSchema.Cardinality.
type ProtoFieldSchemaCardinality string

// ProtoMessageSchema defines model for ProtoMessageSchema.
type ProtoMessageSchema struct {
	Fields []ProtoFieldSchema `json:"fields"`

	// RecursiveRef True when schema expansion stopped due to recursive reference
	RecursiveRef bool `json:"recursiveRef,omitempty"`

	// TypeName Fully-qualified protobuf message type name
	TypeName string `json:"typeName"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Data    any               `json:"data"`
	Headers map[string]string `json:"headers,omitempty"`
	Id      *ID               `json:"id,omitempty"`
	Method  string            `json:"method"`
	Service string            `json:"service"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Code    codes.Code        `json:"code,omitempty"`
	Data    any               `json:"data"`
	Error   string            `json:"error"`
	Headers map[string]string `json:"headers,omitempty"`
}

// Service defines model for Service.
type Service struct {
	Id      string   `json:"id"`
	Methods []Method `json:"methods"`
	Name    string   `json:"name"`
	Package string   `json:"package"`
}

// Sessions defines model for Sessions.
type Sessions struct {
	Sessions []string `json:"sessions"`
}

// Stub defines model for Stub.
type Stub struct {
	// Effects Side effects applied after successful stub match
	Effects []StubEffect `json:"effects,omitempty"`
	Headers StubHeaders  `json:"headers,omitempty"`
	Id      *ID          `json:"id,omitempty"`
	Input   StubInput    `json:"input"`

	// Inputs Inputs to match against. If multiple inputs are provided, the stub will be matched if any of the inputs match.
	Inputs []StubInput `json:"inputs,omitempty"`
	Method string      `json:"method"`

	// Options Optional behavior settings for a stub
	Options *StubOptions `json:"options,omitempty"`
	Output  StubOutput   `json:"output"`

	// Priority Priority of the stub. Higher priority stubs are matched first.
	Priority int    `json:"priority,omitempty"`
	Service  string `json:"service"`

	// Source Source of the stub (file, rest, mcp, proxy)
	Source *string `json:"source,omitempty,omitzero"`
}

// StubEffect defines model for StubEffect.
type StubEffect struct {
	Action StubEffectAction `json:"action"`

	// Id Stub UUID for delete action
	Id string `json:"id,omitempty"`

	// Stub Stub payload for upsert action
	Stub map[string]any `json:"stub,omitempty"`
}

// StubEffectAction defines model for StubEffect.Action.
type StubEffectAction string

// StubHeaders defines model for StubHeaders.
type StubHeaders struct {
	// AnyOf Alternative header matchers (OR logic)
	AnyOf    []StubHeadersAnyOfElement `json:"anyOf,omitempty"`
	Contains map[string]string         `json:"contains,omitempty"`
	Equals   map[string]string         `json:"equals,omitempty"`
	Matches  map[string]string         `json:"matches,omitempty"`
}

// StubHeadersAnyOfElement defines model for StubHeadersAnyOfElement.
type StubHeadersAnyOfElement struct {
	Contains map[string]string `json:"contains,omitempty"`
	Equals   map[string]string `json:"equals,omitempty"`
	Matches  map[string]string `json:"matches,omitempty"`
}

// StubInput defines model for StubInput.
type StubInput struct {
	// AnyOf Alternative input matchers (OR logic)
	AnyOf            []StubInputAnyOfElement `json:"anyOf,omitempty"`
	Contains         map[string]any          `json:"contains,omitempty"`
	Equals           map[string]any          `json:"equals,omitempty"`
	IgnoreArrayOrder bool                    `json:"ignoreArrayOrder,omitempty"`
	Matches          map[string]any          `json:"matches,omitempty"`
}

// StubInputAnyOfElement defines model for StubInputAnyOfElement.
type StubInputAnyOfElement struct {
	Contains         map[string]any `json:"contains,omitempty"`
	Equals           map[string]any `json:"equals,omitempty"`
	IgnoreArrayOrder bool           `json:"ignoreArrayOrder,omitempty"`
	Matches          map[string]any `json:"matches,omitempty"`
}

// StubList defines model for StubList.
type StubList = []Stub

// StubOptions Optional behavior settings for a stub
type StubOptions struct {
	// Times Max number of matches; 0 = unlimited
	Times int `json:"times,omitempty"`
}

// StubOutput defines model for StubOutput.
type StubOutput struct {
	Code codes.Code     `json:"code,omitempty"`
	Data map[string]any `json:"data,omitempty"`

	// Delay Delay before sending the response
	Delay gptypes.Duration `json:"delay,omitempty,omitzero"`

	// Details gRPC status details packed into google.protobuf.Any (each item must contain type URL in `type`)
	Details []StubOutput_Details_Item `json:"details,omitempty"`
	Error   string                    `json:"error,omitempty"`
	Headers map[string]string         `json:"headers,omitempty"`
	Stream  []map[string]any          `json:"stream,omitempty"`
}

// StubOutput_Details_Item defines model for StubOutput.details.Item.
type StubOutput_Details_Item struct {
	// Type Full Any type URL (for example, type.googleapis.com/google.rpc.ErrorInfo)
	Type                 string         `json:"type"`
	AdditionalProperties map[string]any `json:"-"`
}

// VerifyError defines model for VerifyError.
type VerifyError struct {
	Actual   *int    `json:"actual,omitempty"`
	Expected *int    `json:"expected,omitempty"`
	Message  *string `json:"message,omitempty"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	ExpectedCount int    `json:"expectedCount"`
	Method        string `json:"method"`
	Service       string `json:"service"`
}

// ListStubsParams defines parameters for ListStubs.
type ListStubsParams struct {
	// Source Filter by source (file, rest, mcp, proxy)
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Service Filter by service name (exact match)
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// Method Filter by method name (exact match)
	Method *string `form:"method,omitempty" json:"method,omitempty"`

	// Session Filter by session ID (empty means global stubs)
	Session *string `form:"session,omitempty" json:"session,omitempty"`

	// Limit Maximum number of returned stubs
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of stubs to skip before returning results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Sort order for result list
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// AddStubJSONBody defines parameters for AddStub.
type AddStubJSONBody struct {
	union json.RawMessage
}

// AddStubJSONRequestBody defines body for AddStub for application/json ContentType.
type AddStubJSONRequestBody AddStubJSONBody

// BatchStubsDeleteJSONRequestBody defines body for BatchStubsDelete for application/json ContentType.
type BatchStubsDeleteJSONRequestBody = ListID

// InspectStubsJSONRequestBody defines body for InspectStubs for application/json ContentType.
type InspectStubsJSONRequestBody = InspectRequest

// SearchStubsJSONRequestBody defines body for SearchStubs for application/json ContentType.
type SearchStubsJSONRequestBody = SearchRequest

// VerifyCallsJSONRequestBody defines body for VerifyCalls for application/json ContentType.
type VerifyCallsJSONRequestBody = VerifyRequest

// Getter for additional properties for StubOutput_Details_Item. Returns the specified
// element and whether it was found
func (a StubOutput_Details_Item) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StubOutput_Details_Item
func (a *StubOutput_Details_Item) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a *StubOutput_Details_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a StubOutput_Details_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Dashboard aggregate payload
	// (GET /dashboard)
	Dashboard(w http.ResponseWriter, r *http.Request)
	// Dashboard runtime and build info
	// (GET /dashboard/info)
	DashboardInfo(w http.ResponseWriter, r *http.Request)
	// Dashboard overview metrics
	// (GET /dashboard/overview)
	DashboardOverview(w http.ResponseWriter, r *http.Request)
	// List service IDs from REST-added descriptors
	// (GET /descriptors)
	ListDescriptors(w http.ResponseWriter, r *http.Request)
	// Upload FileDescriptorSet
	// (POST /descriptors)
	AddDescriptors(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /health/liveness)
	Liveness(w http.ResponseWriter, r *http.Request)
	// Readiness check
	// (GET /health/readiness)
	Readiness(w http.ResponseWriter, r *http.Request)
	// Get call history
	// (GET /history)
	ListHistory(w http.ResponseWriter, r *http.Request)
	// Services
	// (GET /services)
	ServicesList(w http.ResponseWriter, r *http.Request)
	// Remove service
	// (DELETE /services/{serviceID})
	DeleteService(w http.ResponseWriter, r *http.Request, serviceID string)
	// Service details
	// (GET /services/{serviceID})
	ServiceGet(w http.ResponseWriter, r *http.Request, serviceID string)
	// Service methods
	// (GET /services/{serviceID}/methods)
	ServiceMethodsList(w http.ResponseWriter, r *http.Request, serviceID string)
	// Service method details
	// (GET /services/{serviceID}/methods/{methodID})
	ServiceMethodGet(w http.ResponseWriter, r *http.Request, serviceID string, methodID string)
	// Session options
	// (GET /sessions)
	SessionsList(w http.ResponseWriter, r *http.Request)
	// Remove all stubs
	// (DELETE /stubs)
	PurgeStubs(w http.ResponseWriter, r *http.Request)
	// Getting a list of stubs
	// (GET /stubs)
	ListStubs(w http.ResponseWriter, r *http.Request, params ListStubsParams)
	// Add a new stub to the store
	// (POST /stubs)
	AddStub(w http.ResponseWriter, r *http.Request)
	// Deletes a batch of stubs by IDs
	// (POST /stubs/batchDelete)
	BatchStubsDelete(w http.ResponseWriter, r *http.Request)
	// Inspect stub matching decision path
	// (POST /stubs/inspect)
	InspectStubs(w http.ResponseWriter, r *http.Request)
	// Stub storage search
	// (POST /stubs/search)
	SearchStubs(w http.ResponseWriter, r *http.Request)
	// Getting a list of unused stubs
	// (GET /stubs/unused)
	ListUnusedStubs(w http.ResponseWriter, r *http.Request)
	// Getting a list of used stubs
	// (GET /stubs/used)
	ListUsedStubs(w http.ResponseWriter, r *http.Request)
	// Deletes stub by ID
	// (DELETE /stubs/{uuid})
	DeleteStubByID(w http.ResponseWriter, r *http.Request, uuid ID)
	// Get Stub by ID
	// (GET /stubs/{uuid})
	FindByID(w http.ResponseWriter, r *http.Request, uuid ID)
	// Verify call counts
	// (POST /verify)
	VerifyCalls(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Dashboard operation middleware
func (siw *ServerInterfaceWrapper) Dashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Dashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardInfo operation middleware
func (siw *ServerInterfaceWrapper) DashboardInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardOverview operation middleware
func (siw *ServerInterfaceWrapper) DashboardOverview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardOverview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDescriptors operation middleware
func (siw *ServerInterfaceWrapper) ListDescriptors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDescriptors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddDescriptors operation middleware
func (siw *ServerInterfaceWrapper) AddDescriptors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDescriptors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Liveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHistory operation middleware
func (siw *ServerInterfaceWrapper) ListHistory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHistory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServicesList operation middleware
func (siw *ServerInterfaceWrapper) ServicesList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServicesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceGet(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceMethodsList operation middleware
func (siw *ServerInterfaceWrapper) ServiceMethodsList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceMethodsList(w, r, serviceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceMethodGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceMethodGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceID" -------------
	var serviceID string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceID", mux.Vars(r)["serviceID"], &serviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceID", Err: err})
		return
	}

	// ------------- Path parameter "methodID" -------------
	var methodID string

	err = runtime.BindStyledParameterWithOptions("simple", "methodID", mux.Vars(r)["methodID"], &methodID, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "methodID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceMethodGet(w, r, serviceID, methodID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionsList operation middleware
func (siw *ServerInterfaceWrapper) SessionsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeStubs operation middleware
func (siw *ServerInterfaceWrapper) PurgeStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStubs operation middleware
func (siw *ServerInterfaceWrapper) ListStubs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStubsParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	// ------------- Optional query parameter "service" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service", r.URL.Query(), &params.Service, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "method", r.URL.Query(), &params.Method, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		return
	}

	// ------------- Optional query parameter "session" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "session", r.URL.Query(), &params.Session, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStubs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddStub operation middleware
func (siw *ServerInterfaceWrapper) AddStub(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddStub(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchStubsDelete operation middleware
func (siw *ServerInterfaceWrapper) BatchStubsDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchStubsDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectStubs operation middleware
func (siw *ServerInterfaceWrapper) InspectStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchStubs operation middleware
func (siw *ServerInterfaceWrapper) SearchStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUnusedStubs operation middleware
func (siw *ServerInterfaceWrapper) ListUnusedStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUnusedStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsedStubs operation middleware
func (siw *ServerInterfaceWrapper) ListUsedStubs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsedStubs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStubByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteStubByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid ID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", mux.Vars(r)["uuid"], &uuid, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStubByID(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindByID operation middleware
func (siw *ServerInterfaceWrapper) FindByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid ID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", mux.Vars(r)["uuid"], &uuid, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindByID(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyCalls operation middleware
func (siw *ServerInterfaceWrapper) VerifyCalls(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyCalls(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/dashboard", wrapper.Dashboard).Methods("GET")

	r.HandleFunc(options.BaseURL+"/dashboard/info", wrapper.DashboardInfo).Methods("GET")

	r.HandleFunc(options.BaseURL+"/dashboard/overview", wrapper.DashboardOverview).Methods("GET")

	r.HandleFunc(options.BaseURL+"/descriptors", wrapper.ListDescriptors).Methods("GET")

	r.HandleFunc(options.BaseURL+"/descriptors", wrapper.AddDescriptors).Methods("POST")

	r.HandleFunc(options.BaseURL+"/health/liveness", wrapper.Liveness).Methods("GET")

	r.HandleFunc(options.BaseURL+"/health/readiness", wrapper.Readiness).Methods("GET")

	r.HandleFunc(options.BaseURL+"/history", wrapper.ListHistory).Methods("GET")

	r.HandleFunc(options.BaseURL+"/services", wrapper.ServicesList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/services/{serviceID}", wrapper.DeleteService).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/services/{serviceID}", wrapper.ServiceGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/services/{serviceID}/methods", wrapper.ServiceMethodsList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/services/{serviceID}/methods/{methodID}", wrapper.ServiceMethodGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/sessions", wrapper.SessionsList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.PurgeStubs).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.ListStubs).Methods("GET")

	r.HandleFunc(options.BaseURL+"/stubs", wrapper.AddStub).Methods("POST")

	r.HandleFunc(options.BaseURL+"/stubs/batchDelete", wrapper.BatchStubsDelete).Methods("POST")

	r.HandleFunc(options.BaseURL+"/stubs/inspect", wrapper.InspectStubs).Methods("POST")

	r.HandleFunc(options.BaseURL+"/stubs/search", wrapper.SearchStubs).Methods("POST")

	r.HandleFunc(options.BaseURL+"/stubs/unused", wrapper.ListUnusedStubs).Methods("GET")

	r.HandleFunc(options.BaseURL+"/stubs/used", wrapper.ListUsedStubs).Methods("GET")

	r.HandleFunc(options.BaseURL+"/stubs/{uuid}", wrapper.DeleteStubByID).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/stubs/{uuid}", wrapper.FindByID).Methods("GET")

	r.HandleFunc(options.BaseURL+"/verify", wrapper.VerifyCalls).Methods("POST")

	return r
}
