// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.2
// source: method.proto

package strictmode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayLowerHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayLowerHelloRequest) Reset() {
	*x = SayLowerHelloRequest{}
	mi := &file_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayLowerHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayLowerHelloRequest) ProtoMessage() {}

func (x *SayLowerHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayLowerHelloRequest.ProtoReflect.Descriptor instead.
func (*SayLowerHelloRequest) Descriptor() ([]byte, []int) {
	return file_method_proto_rawDescGZIP(), []int{0}
}

func (x *SayLowerHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayLowerHelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayLowerHelloReply) Reset() {
	*x = SayLowerHelloReply{}
	mi := &file_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayLowerHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayLowerHelloReply) ProtoMessage() {}

func (x *SayLowerHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayLowerHelloReply.ProtoReflect.Descriptor instead.
func (*SayLowerHelloReply) Descriptor() ([]byte, []int) {
	return file_method_proto_rawDescGZIP(), []int{1}
}

func (x *SayLowerHelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayTitleHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayTitleHelloRequest) Reset() {
	*x = SayTitleHelloRequest{}
	mi := &file_method_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayTitleHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayTitleHelloRequest) ProtoMessage() {}

func (x *SayTitleHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_method_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayTitleHelloRequest.ProtoReflect.Descriptor instead.
func (*SayTitleHelloRequest) Descriptor() ([]byte, []int) {
	return file_method_proto_rawDescGZIP(), []int{2}
}

func (x *SayTitleHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayTitleHelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayTitleHelloReply) Reset() {
	*x = SayTitleHelloReply{}
	mi := &file_method_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayTitleHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayTitleHelloReply) ProtoMessage() {}

func (x *SayTitleHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_method_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayTitleHelloReply.ProtoReflect.Descriptor instead.
func (*SayTitleHelloReply) Descriptor() ([]byte, []int) {
	return file_method_proto_rawDescGZIP(), []int{3}
}

func (x *SayTitleHelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_method_proto protoreflect.FileDescriptor

var file_method_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x73, 0x61,
	0x79, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x73, 0x61, 0x79, 0x4c, 0x6f, 0x77,
	0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x61, 0x79, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x61, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xb0, 0x01, 0x0a, 0x08, 0x47, 0x72, 0x69, 0x70, 0x4d, 0x6f, 0x63, 0x6b, 0x12,
	0x51, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x20, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x61,
	0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x2e,
	0x53, 0x61, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x51, 0x0a, 0x0d, 0x73, 0x61, 0x79, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f, 0x64, 0x65,
	0x2e, 0x73, 0x61, 0x79, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f,
	0x64, 0x65, 0x2e, 0x73, 0x61, 0x79, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x76, 0x69, 0x78, 0x2f, 0x67, 0x72, 0x69, 0x70, 0x6d, 0x6f,
	0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_method_proto_rawDescOnce sync.Once
	file_method_proto_rawDescData []byte
)

func file_method_proto_rawDescGZIP() []byte {
	file_method_proto_rawDescOnce.Do(func() {
		file_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_method_proto_rawDesc), len(file_method_proto_rawDesc)))
	})
	return file_method_proto_rawDescData
}

var file_method_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_method_proto_goTypes = []any{
	(*SayLowerHelloRequest)(nil), // 0: strictmode.sayLowerHelloRequest
	(*SayLowerHelloReply)(nil),   // 1: strictmode.sayLowerHelloReply
	(*SayTitleHelloRequest)(nil), // 2: strictmode.SayTitleHelloRequest
	(*SayTitleHelloReply)(nil),   // 3: strictmode.SayTitleHelloReply
}
var file_method_proto_depIdxs = []int32{
	2, // 0: strictmode.GripMock.SayTitleHello:input_type -> strictmode.SayTitleHelloRequest
	0, // 1: strictmode.GripMock.sayLowerHello:input_type -> strictmode.sayLowerHelloRequest
	3, // 2: strictmode.GripMock.SayTitleHello:output_type -> strictmode.SayTitleHelloReply
	1, // 3: strictmode.GripMock.sayLowerHello:output_type -> strictmode.sayLowerHelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_method_proto_init() }
func file_method_proto_init() {
	if File_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_method_proto_rawDesc), len(file_method_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_method_proto_goTypes,
		DependencyIndexes: file_method_proto_depIdxs,
		MessageInfos:      file_method_proto_msgTypes,
	}.Build()
	File_method_proto = out.File
	file_method_proto_goTypes = nil
	file_method_proto_depIdxs = nil
}
