// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: examples/sdk/onboarding/v1/onboarding.proto

package onboardingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Plan          string                 `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignupRequest) Reset() {
	*x = StartSignupRequest{}
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignupRequest) ProtoMessage() {}

func (x *StartSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignupRequest.ProtoReflect.Descriptor instead.
func (*StartSignupRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_onboarding_v1_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *StartSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartSignupRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

type StartSignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NextStep      string                 `protobuf:"bytes,2,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignupResponse) Reset() {
	*x = StartSignupResponse{}
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignupResponse) ProtoMessage() {}

func (x *StartSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignupResponse.ProtoReflect.Descriptor instead.
func (*StartSignupResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_onboarding_v1_onboarding_proto_rawDescGZIP(), []int{1}
}

func (x *StartSignupResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartSignupResponse) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

type ConfirmEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailRequest) Reset() {
	*x = ConfirmEmailRequest{}
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailRequest) ProtoMessage() {}

func (x *ConfirmEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_onboarding_v1_onboarding_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NextStep      string                 `protobuf:"bytes,2,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailResponse) Reset() {
	*x = ConfirmEmailResponse{}
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailResponse) ProtoMessage() {}

func (x *ConfirmEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEmailResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_onboarding_v1_onboarding_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmEmailResponse) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

var File_examples_sdk_onboarding_v1_onboarding_proto protoreflect.FileDescriptor

const file_examples_sdk_onboarding_v1_onboarding_proto_rawDesc = "" +
	"\n" +
	"+examples/sdk/onboarding/v1/onboarding.proto\x12\ronboarding.v1\">\n" +
	"\x12StartSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04plan\x18\x02 \x01(\tR\x04plan\"J\n" +
	"\x13StartSignupResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tnext_step\x18\x02 \x01(\tR\bnextStep\"A\n" +
	"\x13ConfirmEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"K\n" +
	"\x14ConfirmEmailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tnext_step\x18\x02 \x01(\tR\bnextStep2\xc2\x01\n" +
	"\x11OnboardingService\x12T\n" +
	"\vStartSignup\x12!.onboarding.v1.StartSignupRequest\x1a\".onboarding.v1.StartSignupResponse\x12W\n" +
	"\fConfirmEmail\x12\".onboarding.v1.ConfirmEmailRequest\x1a#.onboarding.v1.ConfirmEmailResponseBFZDgithub.com/bavix/gripmock/v3/examples/sdk/onboarding/v1;onboardingv1b\x06proto3"

var (
	file_examples_sdk_onboarding_v1_onboarding_proto_rawDescOnce sync.Once
	file_examples_sdk_onboarding_v1_onboarding_proto_rawDescData []byte
)

func file_examples_sdk_onboarding_v1_onboarding_proto_rawDescGZIP() []byte {
	file_examples_sdk_onboarding_v1_onboarding_proto_rawDescOnce.Do(func() {
		file_examples_sdk_onboarding_v1_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_sdk_onboarding_v1_onboarding_proto_rawDesc), len(file_examples_sdk_onboarding_v1_onboarding_proto_rawDesc)))
	})
	return file_examples_sdk_onboarding_v1_onboarding_proto_rawDescData
}

var file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_sdk_onboarding_v1_onboarding_proto_goTypes = []any{
	(*StartSignupRequest)(nil),   // 0: onboarding.v1.StartSignupRequest
	(*StartSignupResponse)(nil),  // 1: onboarding.v1.StartSignupResponse
	(*ConfirmEmailRequest)(nil),  // 2: onboarding.v1.ConfirmEmailRequest
	(*ConfirmEmailResponse)(nil), // 3: onboarding.v1.ConfirmEmailResponse
}
var file_examples_sdk_onboarding_v1_onboarding_proto_depIdxs = []int32{
	0, // 0: onboarding.v1.OnboardingService.StartSignup:input_type -> onboarding.v1.StartSignupRequest
	2, // 1: onboarding.v1.OnboardingService.ConfirmEmail:input_type -> onboarding.v1.ConfirmEmailRequest
	1, // 2: onboarding.v1.OnboardingService.StartSignup:output_type -> onboarding.v1.StartSignupResponse
	3, // 3: onboarding.v1.OnboardingService.ConfirmEmail:output_type -> onboarding.v1.ConfirmEmailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_sdk_onboarding_v1_onboarding_proto_init() }
func file_examples_sdk_onboarding_v1_onboarding_proto_init() {
	if File_examples_sdk_onboarding_v1_onboarding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_sdk_onboarding_v1_onboarding_proto_rawDesc), len(file_examples_sdk_onboarding_v1_onboarding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_sdk_onboarding_v1_onboarding_proto_goTypes,
		DependencyIndexes: file_examples_sdk_onboarding_v1_onboarding_proto_depIdxs,
		MessageInfos:      file_examples_sdk_onboarding_v1_onboarding_proto_msgTypes,
	}.Build()
	File_examples_sdk_onboarding_v1_onboarding_proto = out.File
	file_examples_sdk_onboarding_v1_onboarding_proto_goTypes = nil
	file_examples_sdk_onboarding_v1_onboarding_proto_depIdxs = nil
}
