package cmd

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/rs/zerolog"
	"github.com/spf13/cobra"
)

const (
	filePerm = 0o600
	shimFile = "zz_gripmock_export.go"
	shimBody = `// Code generated by "gripmock plugin build". DO NOT EDIT.

package main

import "github.com/bavix/gripmock/v3/pkg/plugins/cshared/export"

func init() { export.Use(Register) }

func main() {}
`
)

func init() { //nolint:gochecknoinits
	var output string

	buildCmd := &cobra.Command{
		Use:   "build <package>",
		Short: "Build a plugin from a Go package",
		Long: `Build a Go package into a plugin the server can load: a .so on linux and
macOS, a .dll on windows, where Go has no plugin.Open. The package itself is the
same for both; the windows entry points are added through a build overlay, so
nothing is written into it. Needs a C toolchain.`,
		Args:         cobra.ExactArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPluginBuild(cmd, args[0], output)
		},
	}

	buildCmd.Flags().StringVar(&output, "out", "", "Output file (default: <package name> with the platform extension)")

	pluginCmd := &cobra.Command{Use: "plugin", Short: "Plugin utilities"}
	pluginCmd.AddCommand(buildCmd)
	rootCmd.AddCommand(pluginCmd)
}

func runPluginBuild(cmd *cobra.Command, pkg string, output string) error {
	src, err := filepath.Abs(pkg)
	if err != nil {
		return errors.Wrap(err, "resolve package path")
	}

	if output == "" {
		output = filepath.Base(src) + pluginExt()
	}

	out, err := filepath.Abs(output)
	if err != nil {
		return errors.Wrap(err, "resolve output path")
	}

	ctx := cmd.Context()
	zerolog.Ctx(ctx).Info().Str("package", src).Str("out", out).Msg("building plugin")

	if pluginExt() == ".so" {
		return goBuild(ctx, "plugin", src, out)
	}

	overlay, cleanup, err := writeOverlay(src)
	if err != nil {
		return err
	}

	defer cleanup()

	return goBuild(ctx, "c-shared", src, out, "-overlay", overlay)
}

// writeOverlay hands the entry points to the build as a virtual file, so the
// sources on disk stay exactly as the author wrote them.
func writeOverlay(src string) (string, func(), error) {
	work, err := os.MkdirTemp("", "gripmock-plugin-")
	if err != nil {
		return "", nil, errors.Wrap(err, "create build directory")
	}

	cleanup := func() { _ = os.RemoveAll(work) }

	shim := filepath.Join(work, "export.go")
	overlay := filepath.Join(work, "overlay.json")

	content, err := json.Marshal(map[string]map[string]string{
		"Replace": {filepath.Join(src, shimFile): shim},
	})
	if err == nil {
		err = os.WriteFile(shim, []byte(shimBody), filePerm)
	}

	if err == nil {
		err = os.WriteFile(overlay, content, filePerm)
	}

	if err != nil {
		cleanup()

		return "", nil, errors.Wrap(err, "write build overlay")
	}

	return overlay, cleanup, nil
}

func goBuild(ctx context.Context, mode string, src string, out string, extra ...string) error {
	args := append([]string{"build", "-buildmode=" + mode}, extra...)

	//nolint:gosec // the arguments are the build mode and the paths the user passed in
	build := exec.CommandContext(ctx, "go", append(args, "-o", out, src)...)
	build.Env = append(os.Environ(), "CGO_ENABLED=1")

	combined, err := build.CombinedOutput()
	if err != nil {
		return errors.Wrapf(err, "go build: %s", strings.TrimSpace(string(combined)))
	}

	return nil
}

func pluginExt() string {
	goos := os.Getenv("GOOS")
	if goos == "" {
		goos = runtime.GOOS
	}

	if goos == "windows" {
		return ".dll"
	}

	return ".so"
}
