// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: examples/sdk/telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamSamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSamplesRequest) Reset() {
	*x = StreamSamplesRequest{}
	mi := &file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSamplesRequest) ProtoMessage() {}

func (x *StreamSamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSamplesRequest.ProtoReflect.Descriptor instead.
func (*StreamSamplesRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *StreamSamplesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StreamSamplesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type StreamSamplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSamplesResponse) Reset() {
	*x = StreamSamplesResponse{}
	mi := &file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSamplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSamplesResponse) ProtoMessage() {}

func (x *StreamSamplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSamplesResponse.ProtoReflect.Descriptor instead.
func (*StreamSamplesResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *StreamSamplesResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamSamplesResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StreamSamplesResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_examples_sdk_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_examples_sdk_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	")examples/sdk/telemetry/v1/telemetry.proto\x12\ftelemetry.v1\"K\n" +
	"\x14StreamSamplesRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\"]\n" +
	"\x15StreamSamplesResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit2n\n" +
	"\x10TelemetryService\x12Z\n" +
	"\rStreamSamples\x12\".telemetry.v1.StreamSamplesRequest\x1a#.telemetry.v1.StreamSamplesResponse0\x01BDZBgithub.com/bavix/gripmock/v3/examples/sdk/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_examples_sdk_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_examples_sdk_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_examples_sdk_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_examples_sdk_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_examples_sdk_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_sdk_telemetry_v1_telemetry_proto_rawDesc), len(file_examples_sdk_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_examples_sdk_telemetry_v1_telemetry_proto_rawDescData
}

var file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_sdk_telemetry_v1_telemetry_proto_goTypes = []any{
	(*StreamSamplesRequest)(nil),  // 0: telemetry.v1.StreamSamplesRequest
	(*StreamSamplesResponse)(nil), // 1: telemetry.v1.StreamSamplesResponse
}
var file_examples_sdk_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.TelemetryService.StreamSamples:input_type -> telemetry.v1.StreamSamplesRequest
	1, // 1: telemetry.v1.TelemetryService.StreamSamples:output_type -> telemetry.v1.StreamSamplesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_sdk_telemetry_v1_telemetry_proto_init() }
func file_examples_sdk_telemetry_v1_telemetry_proto_init() {
	if File_examples_sdk_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_sdk_telemetry_v1_telemetry_proto_rawDesc), len(file_examples_sdk_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_sdk_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_examples_sdk_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_examples_sdk_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_examples_sdk_telemetry_v1_telemetry_proto = out.File
	file_examples_sdk_telemetry_v1_telemetry_proto_goTypes = nil
	file_examples_sdk_telemetry_v1_telemetry_proto_depIdxs = nil
}
