// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: wkt.proto

package well_known_types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	apipb "google.golang.org/protobuf/types/known/apipb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiInfoV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time          *date.Date             `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiInfoV2Request) Reset() {
	*x = ApiInfoV2Request{}
	mi := &file_wkt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiInfoV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiInfoV2Request) ProtoMessage() {}

func (x *ApiInfoV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_wkt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiInfoV2Request.ProtoReflect.Descriptor instead.
func (*ApiInfoV2Request) Descriptor() ([]byte, []int) {
	return file_wkt_proto_rawDescGZIP(), []int{0}
}

func (x *ApiInfoV2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiInfoV2Request) GetTime() *date.Date {
	if x != nil {
		return x.Time
	}
	return nil
}

type ApiInfoV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiInfoV2Response) Reset() {
	*x = ApiInfoV2Response{}
	mi := &file_wkt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiInfoV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiInfoV2Response) ProtoMessage() {}

func (x *ApiInfoV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_wkt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiInfoV2Response.ProtoReflect.Descriptor instead.
func (*ApiInfoV2Response) Descriptor() ([]byte, []int) {
	return file_wkt_proto_rawDescGZIP(), []int{1}
}

var File_wkt_proto protoreflect.FileDescriptor

const file_wkt_proto_rawDesc = "" +
	"\n" +
	"\twkt.proto\x12\x10well_known_types\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/api.proto\x1a\x16google/type/date.proto\"M\n" +
	"\x10ApiInfoV2Request\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04time\x18\x02 \x01(\v2\x11.google.type.DateR\x04time\"\x13\n" +
	"\x11ApiInfoV2Response2\xdd\x01\n" +
	"\bGripmock\x12Y\n" +
	"\aApiInfo\x12\x16.google.protobuf.Empty\x1a\x14.google.protobuf.Api\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/gripmock/api-info\x12v\n" +
	"\tApiInfoV2\x12\".well_known_types.ApiInfoV2Request\x1a#.well_known_types.ApiInfoV2Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/gripmock/api-infoB=Z;github.com/bavix/gripmock/protogen/example/well_known_typesb\x06proto3"

var (
	file_wkt_proto_rawDescOnce sync.Once
	file_wkt_proto_rawDescData []byte
)

func file_wkt_proto_rawDescGZIP() []byte {
	file_wkt_proto_rawDescOnce.Do(func() {
		file_wkt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wkt_proto_rawDesc), len(file_wkt_proto_rawDesc)))
	})
	return file_wkt_proto_rawDescData
}

var file_wkt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wkt_proto_goTypes = []any{
	(*ApiInfoV2Request)(nil),  // 0: well_known_types.ApiInfoV2Request
	(*ApiInfoV2Response)(nil), // 1: well_known_types.ApiInfoV2Response
	(*date.Date)(nil),         // 2: google.type.Date
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
	(*apipb.Api)(nil),         // 4: google.protobuf.Api
}
var file_wkt_proto_depIdxs = []int32{
	2, // 0: well_known_types.ApiInfoV2Request.time:type_name -> google.type.Date
	3, // 1: well_known_types.Gripmock.ApiInfo:input_type -> google.protobuf.Empty
	0, // 2: well_known_types.Gripmock.ApiInfoV2:input_type -> well_known_types.ApiInfoV2Request
	4, // 3: well_known_types.Gripmock.ApiInfo:output_type -> google.protobuf.Api
	1, // 4: well_known_types.Gripmock.ApiInfoV2:output_type -> well_known_types.ApiInfoV2Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wkt_proto_init() }
func file_wkt_proto_init() {
	if File_wkt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wkt_proto_rawDesc), len(file_wkt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wkt_proto_goTypes,
		DependencyIndexes: file_wkt_proto_depIdxs,
		MessageInfos:      file_wkt_proto_msgTypes,
	}.Build()
	File_wkt_proto = out.File
	file_wkt_proto_goTypes = nil
	file_wkt_proto_depIdxs = nil
}
