// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: examples/sdk/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeInvoiceRequest) Reset() {
	*x = ChargeInvoiceRequest{}
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeInvoiceRequest) ProtoMessage() {}

func (x *ChargeInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeInvoiceRequest.ProtoReflect.Descriptor instead.
func (*ChargeInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *ChargeInvoiceRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ChargeInvoiceRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type ChargeInvoiceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RemainingCents int64                  `protobuf:"varint,3,opt,name=remaining_cents,json=remainingCents,proto3" json:"remaining_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChargeInvoiceResponse) Reset() {
	*x = ChargeInvoiceResponse{}
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeInvoiceResponse) ProtoMessage() {}

func (x *ChargeInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeInvoiceResponse.ProtoReflect.Descriptor instead.
func (*ChargeInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeInvoiceResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ChargeInvoiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChargeInvoiceResponse) GetRemainingCents() int64 {
	if x != nil {
		return x.RemainingCents
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_examples_sdk_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceCents  int64                  `protobuf:"varint,1,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_sdk_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_examples_sdk_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_examples_sdk_billing_v1_billing_proto protoreflect.FileDescriptor

const file_examples_sdk_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"%examples/sdk/billing/v1/billing.proto\x12\n" +
	"billing.v1\"y\n" +
	"\x14ChargeInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\"\x7f\n" +
	"\x15ChargeInvoiceResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fremaining_cents\x18\x03 \x01(\x03R\x0eremainingCents\"4\n" +
	"\x11GetBalanceRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"U\n" +
	"\x12GetBalanceResponse\x12#\n" +
	"\rbalance_cents\x18\x01 \x01(\x03R\fbalanceCents\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency2\xb3\x01\n" +
	"\x0eBillingService\x12T\n" +
	"\rChargeInvoice\x12 .billing.v1.ChargeInvoiceRequest\x1a!.billing.v1.ChargeInvoiceResponse\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.billing.v1.GetBalanceRequest\x1a\x1e.billing.v1.GetBalanceResponseB@Z>github.com/bavix/gripmock/v3/examples/sdk/billing/v1;billingv1b\x06proto3"

var (
	file_examples_sdk_billing_v1_billing_proto_rawDescOnce sync.Once
	file_examples_sdk_billing_v1_billing_proto_rawDescData []byte
)

func file_examples_sdk_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_examples_sdk_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_examples_sdk_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_sdk_billing_v1_billing_proto_rawDesc), len(file_examples_sdk_billing_v1_billing_proto_rawDesc)))
	})
	return file_examples_sdk_billing_v1_billing_proto_rawDescData
}

var file_examples_sdk_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_sdk_billing_v1_billing_proto_goTypes = []any{
	(*ChargeInvoiceRequest)(nil),  // 0: billing.v1.ChargeInvoiceRequest
	(*ChargeInvoiceResponse)(nil), // 1: billing.v1.ChargeInvoiceResponse
	(*GetBalanceRequest)(nil),     // 2: billing.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 3: billing.v1.GetBalanceResponse
}
var file_examples_sdk_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: billing.v1.BillingService.ChargeInvoice:input_type -> billing.v1.ChargeInvoiceRequest
	2, // 1: billing.v1.BillingService.GetBalance:input_type -> billing.v1.GetBalanceRequest
	1, // 2: billing.v1.BillingService.ChargeInvoice:output_type -> billing.v1.ChargeInvoiceResponse
	3, // 3: billing.v1.BillingService.GetBalance:output_type -> billing.v1.GetBalanceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_sdk_billing_v1_billing_proto_init() }
func file_examples_sdk_billing_v1_billing_proto_init() {
	if File_examples_sdk_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_sdk_billing_v1_billing_proto_rawDesc), len(file_examples_sdk_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_sdk_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_examples_sdk_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_examples_sdk_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_examples_sdk_billing_v1_billing_proto = out.File
	file_examples_sdk_billing_v1_billing_proto_goTypes = nil
	file_examples_sdk_billing_v1_billing_proto_depIdxs = nil
}
